macro_rules! cli_message_ids {
    () => {
        MsgId::CliHelpAbout
        | MsgId::CliHelpUsageHeading
        | MsgId::CliHelpCommandsHeading
        | MsgId::CliHelpArgumentsHeading
        | MsgId::CliHelpOptionsHeading
        | MsgId::CliHelpCommandValidate
        | MsgId::CliHelpCommandCompile
        | MsgId::CliHelpCommandExtract
        | MsgId::CliHelpCommandCheckIds
        | MsgId::CliHelpCommandCheckMarkup
        | MsgId::CliHelpCommandCheckMetadata
        | MsgId::CliHelpCommandValidateProject
        | MsgId::CliHelpCommandCheckFresh
        | MsgId::CliHelpCommandInspectSchema
        | MsgId::CliHelpCommandExplain
        | MsgId::CliHelpCommandWatch
        | MsgId::CliHelpCommandRun
        | MsgId::CliHelpCommandTrace
        | MsgId::CliHelpCommandPlay
        | MsgId::CliHelpCommandBench
        | MsgId::CliHelpArgPaths
        | MsgId::CliHelpArgSchema
        | MsgId::CliHelpArgSchemaInspection
        | MsgId::CliHelpArgProjectRoot
        | MsgId::CliHelpArgDiagnosticCode
        | MsgId::CliHelpArgOutputCompile
        | MsgId::CliHelpArgOutputExtract
        | MsgId::CliHelpArgAssetRun
        | MsgId::CliHelpArgAssetPlay
        | MsgId::CliHelpArgBlock
        | MsgId::CliHelpArgFixture
        | MsgId::CliHelpArgUi
        | MsgId::CliHelpArgKeymap
        | MsgId::CliHelpArgDialogueLocale
        | MsgId::CliHelpArgDialogueCatalog
        | MsgId::CliHelpArgBenchScale
        | MsgId::CliHelpArgBenchGroup
        | MsgId::CliHelpArgBenchFormat
        | MsgId::CliHelpArgBenchOutput
        | MsgId::CliHelpArgBenchBaseline
        | MsgId::CliHelpArgBenchSamples
        | MsgId::ExplainCode
        | MsgId::ExplainCategory
        | MsgId::ExplainMeaning
        | MsgId::ExplainCommonCauses
        | MsgId::ExplainHowToFix
        | MsgId::ExplainListItem
        | MsgId::WatchBuilding
        | MsgId::WatchWaitingForChanges
        | MsgId::WatchRebuilding
        | MsgId::WatchBuildSucceeded
        | MsgId::WatchBuildDurationMicroseconds
        | MsgId::WatchBuildDurationMilliseconds
        | MsgId::WatchBuildFailedWaiting
        | MsgId::WatchBuildFailed
        | MsgId::WatchBuildFailedPartial
        | MsgId::WatchBuildFailedIndeterminate
        | MsgId::WatchBuildFailedRefused
        | MsgId::WatchBuildFailedNotAttempted
        | MsgId::WatchBuildFailedPublished
        | MsgId::WatchBuildFailedUnsupported
        | MsgId::WatchBuildFailedPartialWithFailure
        | MsgId::WatchBuildFailedIndeterminateWithFailure
        | MsgId::WatchBuildFailedRefusedWithFailure
        | MsgId::WatchBuildFailedNotAttemptedWithFailure
        | MsgId::WatchBuildFailedPublishedWithFailure
        | MsgId::WatchBuildFailedUnsupportedWithFailure
        | MsgId::WatchBuildStatusSucceeded
        | MsgId::WatchBuildStatusFailed
        | MsgId::WatchBuildStatusStale
        | MsgId::WatchBuildStatusCancelled
        | MsgId::WatchBuildStatusSuperseded
        | MsgId::WatchBuildStatusUnknown
        | MsgId::WatchBuildRecoveryTargetsEmpty
        | MsgId::WatchBuildRecoveryTargetsList
        | MsgId::WatchBuildRecoveryRequired
        | MsgId::WatchBuildRecoveryNotice
        | MsgId::WatchBuildRecoverySummary
        | MsgId::WatchBuildRecoveryRecord
        | MsgId::WatchBuildRecoveryReasonStageCleanup
        | MsgId::WatchBuildRecoveryReasonPublicationIndeterminate
        | MsgId::WatchBuildRecoveryReasonPublicationUncommitted
        | MsgId::WatchBuildRecoveryReasonUnknown
        | MsgId::WatchBuildRecoveryDetailIo
        | MsgId::WatchBuildRecoveryIoAlreadyExists
        | MsgId::WatchBuildRecoveryIoInvalidInput
        | MsgId::WatchBuildRecoveryIoNotFound
        | MsgId::WatchBuildRecoveryIoPermissionDenied
        | MsgId::WatchBuildRecoveryIoOther
        | MsgId::WatchBuildFailureCheckRequestMismatch
        | MsgId::WatchBuildFailureCheckFreshnessMismatch
        | MsgId::WatchBuildFailureCheckUnknown
        | MsgId::WatchBuildFailureDiagnostics
        | MsgId::WatchBuildFailureUnknown
        | MsgId::WatchBuildFailureEngineInvalidOutput
        | MsgId::WatchBuildFailureEngineHost
        | MsgId::WatchBuildFailureEngineUnknown
        | MsgId::WatchBuildFailureDuplicateTarget
        | MsgId::WatchBuildFailurePreparation
        | MsgId::WatchBuildFailureReasonRejected
        | MsgId::WatchBuildFailureReasonStorage
        | MsgId::WatchBuildFailureReasonUnknown
        | MsgId::WatchBuildFailureInvalidPublishedPartition
        | MsgId::WatchBuildFailureInvalidPartialPartition
        | MsgId::WatchBuildFailureInvalidRecoveryTarget
        | MsgId::WatchBuildFailureInvalidNotCommitted
        | MsgId::WatchBuildFailureInvalidUnknown
        | MsgId::WatchBuildFailureRefusalStaleBuildGeneration
        | MsgId::WatchBuildFailureRefusalStaleSnapshotGeneration
        | MsgId::WatchBuildFailureRefusalStaleFingerprints
        | MsgId::WatchBuildFailureRefusalRequestIdentityMismatch
        | MsgId::WatchBuildFailureRefusalUnknown
        | MsgId::WatchBuildFailureNotAttemptedBuildFailed
        | MsgId::WatchBuildFailureNotAttemptedCancelled
        | MsgId::WatchBuildFailureNotAttemptedSuperseded
        | MsgId::WatchBuildFailureNotAttemptedStale
        | MsgId::WatchBuildFailureNotAttemptedNoCandidates
        | MsgId::WatchBuildFailureNotAttemptedPreparationFailed
        | MsgId::WatchBuildFailureNotAttemptedInvalidOutcome
        | MsgId::WatchBuildFailureNotAttemptedUnknown
        | MsgId::WatchEventError
        | MsgId::CliHelpArgHelp
        | MsgId::CliHelpArgVersion
        | MsgId::PlayTuiStarting
        | MsgId::PlayStart
        | MsgId::PlayLine
        | MsgId::PlayPromptLine
        | MsgId::PlayPrompt
        | MsgId::PlayChoiceRow
        | MsgId::PlayChoicePrompt
        | MsgId::PlayConditionPrompt
        | MsgId::PlayConditionResult
        | MsgId::PlaySelectedChoice
        | MsgId::PlayEffect
        | MsgId::PlayAckPrompt
        | MsgId::PlayAckCompleted
        | MsgId::PlayEnd
        | MsgId::PlayDeferredEffects
        | MsgId::PlayDeferredEffectRow
        | MsgId::PlayInvalidInput
        | MsgId::PlayErrorEnterYOrN
        | MsgId::PlayErrorEnterEnumVariant
        | MsgId::PlayErrorPressEnterOrAck
        | MsgId::PlayErrorEmptyChoice
        | MsgId::PlayErrorChoiceIndexOutOfRange
        | MsgId::PlayErrorChoiceIdInvalid
        | MsgId::PlayErrorChoiceIdUnavailable
        | MsgId::PlayErrorChoiceUnavailable
        | MsgId::PlayErrorChoiceUnavailableReason
        | MsgId::CliErrorPlayEof
        | MsgId::CliErrorPlayInvalidInput
        | MsgId::CliErrorPlayInterrupted
        | MsgId::CliErrorPlayTuiRequiresTerminal
        | MsgId::CliErrorUiConfigRead
        | MsgId::CliErrorUiConfigToml
        | MsgId::CliErrorUiLocaleInvalid
        | MsgId::CliErrorDialogueCatalogConflict
        | MsgId::CliErrorDialogueCatalogPluralFormsConflict
        | MsgId::CliErrorDialogueCatalogMalformed
        | MsgId::CliErrorDialogueCatalogMissingLocale
        | MsgId::CliErrorDialogueCatalogSpecInvalid
        | MsgId::CliErrorDialogueLocaleInvalid
        | MsgId::CliErrorGeneric
        | MsgId::CliErrorDiagnosticRendering
        | MsgId::CliErrorDiagnosticCodeMalformed
        | MsgId::CliErrorDiagnosticCodeUnknown
        | MsgId::CliErrorUiCatalog
        | MsgId::CliErrorBench
        | MsgId::CliErrorBenchmark
        | MsgId::CliErrorDialogueCatalogReasonExpectedDirective
        | MsgId::CliErrorDialogueCatalogReasonExpectedQuotedString
        | MsgId::CliErrorDialogueCatalogReasonMissingContext
        | MsgId::CliErrorDialogueCatalogReasonMissingId
        | MsgId::CliErrorDialogueCatalogReasonMissingTranslation
        | MsgId::CliErrorDialogueCatalogReasonInvalidHeader
        | MsgId::CliErrorDialogueCatalogReasonInvalidPluralRule
        | MsgId::CliErrorDialogueCatalogReasonInvalidStableId
        | MsgId::CliErrorDialogueCatalogReasonDuplicateField
        | MsgId::CliErrorDialogueCatalogReasonDuplicateEntry
        | MsgId::CliErrorDialogueCatalogReasonInvalidFieldOrder
        | MsgId::CliErrorDialogueCatalogReasonPlaceholderMismatch
        | MsgId::CliErrorDialogueCatalogReasonPluralEntriesUnsupported
        | MsgId::CliErrorDialogueCatalogReasonQuotedContinuationWithoutField
        | MsgId::CliErrorDialogueCatalogReasonUnexpectedTextAfterQuotedString
        | MsgId::CliErrorDialogueCatalogReasonUnterminatedQuotedString
        | MsgId::CliErrorDialogueCatalogReasonUnsupportedEscape
        | MsgId::CliErrorDecodeAsset
        | MsgId::CliErrorAssetMetadata
        | MsgId::CliErrorAssetNotFile
        | MsgId::CliErrorMalformedCompiledAsset
        | MsgId::CliErrorDiagnostics
        | MsgId::CliErrorFixtureChoiceIndex
        | MsgId::CliErrorFixtureChoiceNotInPrompt
        | MsgId::CliErrorAmbiguousFixtureChoice
        | MsgId::CliErrorFixtureToml
        | MsgId::CliErrorMissingPath
        | MsgId::CliErrorMissingFixtureChoice
        | MsgId::CliErrorNoInputs
        | MsgId::CliErrorOutputOverwritesInput
        | MsgId::CliErrorBlockingEffect
        | MsgId::CliErrorBenchJson
        | MsgId::CliErrorTraceJson
        | MsgId::CliErrorSchemaInspectionJson
        | MsgId::CliErrorSchemaInspectionUnsupportedFormat
        | MsgId::CliErrorSchemaInspectionMalformed
        | MsgId::CliErrorSchemaInspectionInvalidSummary
        | MsgId::CliErrorUnknownPrompt
        | MsgId::CliErrorRead
        | MsgId::CliErrorReadDir
        | MsgId::CliErrorWrite
        | MsgId::CliErrorWatch
        | MsgId::RunEffect
    };
}
