macro_rules! cli_message_ids {
    () => {
        MsgId::CliHelpAbout
        | MsgId::CliHelpUsageHeading
        | MsgId::CliHelpCommandsHeading
        | MsgId::CliHelpArgumentsHeading
        | MsgId::CliHelpOptionsHeading
        | MsgId::CliHelpCommandValidate
        | MsgId::CliHelpCommandCompile
        | MsgId::CliHelpCommandExtract
        | MsgId::CliHelpCommandCheckIds
        | MsgId::CliHelpCommandCheckMarkup
        | MsgId::CliHelpCommandCheckMetadata
        | MsgId::CliHelpCommandValidateProject
        | MsgId::CliHelpCommandCheckFresh
        | MsgId::CliHelpCommandExplain
        | MsgId::CliHelpCommandWatch
        | MsgId::CliHelpCommandRun
        | MsgId::CliHelpCommandTrace
        | MsgId::CliHelpCommandPlay
        | MsgId::CliHelpCommandBench
        | MsgId::CliHelpArgPaths
        | MsgId::CliHelpArgSchema
        | MsgId::CliHelpArgProjectRoot
        | MsgId::CliHelpArgDiagnosticCode
        | MsgId::CliHelpArgOutputCompile
        | MsgId::CliHelpArgOutputExtract
        | MsgId::CliHelpArgAssetRun
        | MsgId::CliHelpArgAssetPlay
        | MsgId::CliHelpArgBlock
        | MsgId::CliHelpArgFixture
        | MsgId::CliHelpArgUi
        | MsgId::CliHelpArgKeymap
        | MsgId::CliHelpArgDialogueLocale
        | MsgId::CliHelpArgDialogueCatalog
        | MsgId::CliHelpArgBenchScale
        | MsgId::CliHelpArgBenchGroup
        | MsgId::CliHelpArgBenchFormat
        | MsgId::CliHelpArgBenchOutput
        | MsgId::CliHelpArgBenchBaseline
        | MsgId::CliHelpArgBenchSamples
        | MsgId::ExplainCode
        | MsgId::ExplainCategory
        | MsgId::ExplainMeaning
        | MsgId::ExplainCommonCauses
        | MsgId::ExplainHowToFix
        | MsgId::ExplainListItem
        | MsgId::WatchBuilding
        | MsgId::WatchWaitingForChanges
        | MsgId::WatchRebuilding
        | MsgId::WatchBuildSucceeded
        | MsgId::WatchBuildFailedWaiting
        | MsgId::WatchBuildFailed
        | MsgId::WatchEventError
        | MsgId::CliHelpArgHelp
        | MsgId::CliHelpArgVersion
        | MsgId::PlayTuiStarting
        | MsgId::PlayStart
        | MsgId::PlayLine
        | MsgId::PlayPromptLine
        | MsgId::PlayPrompt
        | MsgId::PlayChoiceRow
        | MsgId::PlayChoicePrompt
        | MsgId::PlayConditionPrompt
        | MsgId::PlayConditionResult
        | MsgId::PlaySelectedChoice
        | MsgId::PlayEffect
        | MsgId::PlayAckPrompt
        | MsgId::PlayAckCompleted
        | MsgId::PlayEnd
        | MsgId::PlayDeferredEffects
        | MsgId::PlayDeferredEffectRow
        | MsgId::PlayInvalidInput
        | MsgId::PlayErrorEnterYOrN
        | MsgId::PlayErrorEnterEnumVariant
        | MsgId::PlayErrorPressEnterOrAck
        | MsgId::PlayErrorEmptyChoice
        | MsgId::PlayErrorChoiceIndexOutOfRange
        | MsgId::PlayErrorChoiceIdInvalid
        | MsgId::PlayErrorChoiceIdUnavailable
        | MsgId::PlayErrorChoiceUnavailable
        | MsgId::PlayErrorChoiceUnavailableReason
        | MsgId::CliErrorPlayEof
        | MsgId::CliErrorPlayInvalidInput
        | MsgId::CliErrorPlayInterrupted
        | MsgId::CliErrorPlayTuiRequiresTerminal
        | MsgId::CliErrorUiConfigRead
        | MsgId::CliErrorUiConfigToml
        | MsgId::CliErrorUiLocaleInvalid
        | MsgId::CliErrorDialogueCatalogConflict
        | MsgId::CliErrorDialogueCatalogPluralFormsConflict
        | MsgId::CliErrorDialogueCatalogMalformed
        | MsgId::CliErrorDialogueCatalogMissingLocale
        | MsgId::CliErrorDialogueCatalogSpecInvalid
        | MsgId::CliErrorDialogueLocaleInvalid
        | MsgId::CliErrorGeneric
        | MsgId::CliErrorDiagnosticRendering
        | MsgId::CliErrorDiagnosticCodeMalformed
        | MsgId::CliErrorDiagnosticCodeUnknown
        | MsgId::CliErrorUiCatalog
        | MsgId::CliErrorBench
        | MsgId::CliErrorBenchmark
        | MsgId::CliErrorDialogueCatalogReasonExpectedDirective
        | MsgId::CliErrorDialogueCatalogReasonExpectedQuotedString
        | MsgId::CliErrorDialogueCatalogReasonMissingContext
        | MsgId::CliErrorDialogueCatalogReasonMissingId
        | MsgId::CliErrorDialogueCatalogReasonMissingTranslation
        | MsgId::CliErrorDialogueCatalogReasonInvalidHeader
        | MsgId::CliErrorDialogueCatalogReasonInvalidPluralRule
        | MsgId::CliErrorDialogueCatalogReasonInvalidStableId
        | MsgId::CliErrorDialogueCatalogReasonDuplicateField
        | MsgId::CliErrorDialogueCatalogReasonDuplicateEntry
        | MsgId::CliErrorDialogueCatalogReasonInvalidFieldOrder
        | MsgId::CliErrorDialogueCatalogReasonPlaceholderMismatch
        | MsgId::CliErrorDialogueCatalogReasonPluralEntriesUnsupported
        | MsgId::CliErrorDialogueCatalogReasonQuotedContinuationWithoutField
        | MsgId::CliErrorDialogueCatalogReasonUnexpectedTextAfterQuotedString
        | MsgId::CliErrorDialogueCatalogReasonUnterminatedQuotedString
        | MsgId::CliErrorDialogueCatalogReasonUnsupportedEscape
        | MsgId::CliErrorDecodeAsset
        | MsgId::CliErrorAssetMetadata
        | MsgId::CliErrorAssetNotFile
        | MsgId::CliErrorMalformedCompiledAsset
        | MsgId::CliErrorDiagnostics
        | MsgId::CliErrorFixtureChoiceIndex
        | MsgId::CliErrorFixtureChoiceNotInPrompt
        | MsgId::CliErrorFixtureToml
        | MsgId::CliErrorMissingPath
        | MsgId::CliErrorMissingFixtureChoice
        | MsgId::CliErrorNoInputs
        | MsgId::CliErrorOutputOverwritesInput
        | MsgId::CliErrorBlockingEffect
        | MsgId::CliErrorBenchJson
        | MsgId::CliErrorTraceJson
        | MsgId::CliErrorUnknownPrompt
        | MsgId::CliErrorRead
        | MsgId::CliErrorReadDir
        | MsgId::CliErrorWrite
        | MsgId::CliErrorWatch
        | MsgId::RunEffect
    };
}
