macro_rules! tui_message_ids {
    () => {
        MsgId::TuiReady
        | MsgId::TuiFinished
        | MsgId::TuiCommand
        | MsgId::TuiCommandWithValue
        | MsgId::TuiUnknownCommand
        | MsgId::TuiChoiceInputPrefix
        | MsgId::TuiChoiceInput
        | MsgId::TuiEnumVariantInput
        | MsgId::TuiConditionYesRow
        | MsgId::TuiConditionNoRow
        | MsgId::TuiConditionYesShortcutRow
        | MsgId::TuiConditionNoShortcutRow
        | MsgId::TuiEnumConditionHint
        | MsgId::TuiAckEnterHint
        | MsgId::TuiHeaderTitle
        | MsgId::TuiHeaderAsset
        | MsgId::TuiHeaderBlock
        | MsgId::TuiWaiting
        | MsgId::TuiMetadataMode
        | MsgId::TuiMetadataRuntimeEffectId
        | MsgId::TuiMetadataFunction
        | MsgId::TuiMetadataArgs
        | MsgId::TuiInputAnswer
        | MsgId::TuiInputEnumVariant
        | MsgId::TuiInputAck
        | MsgId::TuiInputChoice
        | MsgId::TuiChoiceUnavailable
        | MsgId::TuiChoiceUnavailableReason
        | MsgId::TuiDeferredQueueTitle
        | MsgId::TuiDeferredQueueScheduled
        | MsgId::TuiDeferredQueueReadyAtEnd
        | MsgId::TuiTranscriptLine
        | MsgId::TuiTranscriptPrompt
        | MsgId::TuiTranscriptChoice
        | MsgId::TuiTranscriptCondition
        | MsgId::TuiTranscriptEffect
        | MsgId::TuiTranscriptAck
        | MsgId::TuiTranscriptDeferred
        | MsgId::TuiTranscriptEnd
        | MsgId::TuiTranscriptCompleted
        | MsgId::TuiTranscriptEffectText
        | MsgId::TuiTranscriptDeferredEffectText
        | MsgId::TuiTranscriptDeferredEffects
        | MsgId::TuiHelpTitle
        | MsgId::TuiHelpKeyHeading
        | MsgId::TuiHelpActionHeading
        | MsgId::TuiHelpDescriptionHeading
        | MsgId::TuiHelpActionClose
        | MsgId::TuiHelpActionQuit
        | MsgId::TuiHelpActionMove
        | MsgId::TuiHelpActionSubmit
        | MsgId::TuiHelpActionInput
        | MsgId::TuiHelpActionShortcut
        | MsgId::TuiHelpActionCommand
        | MsgId::TuiHelpActionHelp
        | MsgId::TuiHelpActionQueue
        | MsgId::TuiHelpDescriptionClose
        | MsgId::TuiHelpDescriptionOpenHelp
        | MsgId::TuiHelpDescriptionQuit
        | MsgId::TuiHelpDescriptionInterrupt
        | MsgId::TuiHelpDescriptionMoveChoice
        | MsgId::TuiHelpDescriptionSubmitChoice
        | MsgId::TuiHelpDescriptionInputChoice
        | MsgId::TuiHelpDescriptionMoveCondition
        | MsgId::TuiHelpDescriptionShortcutCondition
        | MsgId::TuiHelpDescriptionSubmitCondition
        | MsgId::TuiHelpDescriptionInputEnumCondition
        | MsgId::TuiHelpDescriptionSubmitEnumCondition
        | MsgId::TuiHelpDescriptionSubmitEffect
        | MsgId::TuiHelpDescriptionFinished
        | MsgId::TuiHelpDescriptionCommand
        | MsgId::TuiHelpDescriptionQueue
        | MsgId::TuiFooterCommand
    };
}
