use super::{Client, MsgId};

// Keep each client registry in its own domain-owned table while this module
// retains the one exhaustive dispatch point used by UiContract.
include!("ownership/cli.rs");
include!("ownership/tui.rs");
include!("ownership/lsp.rs");
include!("ownership/neovim.rs");

macro_rules! vscode_command_message_ids {
    () => {
        MsgId::VscodeCommandValidateTitle
            | MsgId::VscodeCommandCompileTitle
            | MsgId::VscodeCommandExtractTitle
            | MsgId::VscodeCommandWatchStartTitle
            | MsgId::VscodeCommandWatchStopTitle
            | MsgId::VscodeCommandRunTitle
            | MsgId::VscodeCommandTraceTitle
            | MsgId::VscodeCommandCliPathDescription
            | MsgId::VscodeCommandUntrusted
            | MsgId::VscodeCommandDocumentRequired
            | MsgId::VscodeCommandDocumentUnsaved
            | MsgId::VscodeCommandDocumentUntitled
            | MsgId::VscodeCommandDocumentChanged
            | MsgId::VscodeCommandDocumentOutsideRoot
            | MsgId::VscodeCommandWorkspaceRequired
            | MsgId::VscodeCommandCliPathInvalid
            | MsgId::VscodeCommandInputInvalid
            | MsgId::VscodeCommandWatchRunning
            | MsgId::VscodeCommandWatchNotRunning
            | MsgId::VscodeCommandWatchStopTimeout
            | MsgId::VscodeCommandResult
            | MsgId::VscodeCommandContentDiagnostics
            | MsgId::VscodeCommandFailure
            | MsgId::VscodeCommandProtocolFailure
            | MsgId::VscodeCommandWatchStatus
            | MsgId::VscodeCommandCompileOutputTitle
            | MsgId::VscodeCommandExtractOutputTitle
            | MsgId::VscodeCommandAssetTitle
            | MsgId::VscodeCommandAssetFilter
            | MsgId::VscodeCommandBlockTitle
            | MsgId::VscodeCommandBlockPrompt
            | MsgId::VscodeCommandBlockPlaceholder
            | MsgId::VscodeCommandFixtureTitle
            | MsgId::VscodeCommandFixtureFilter
            | MsgId::VscodeCommandRenameTitle
            | MsgId::VscodeCommandRenameCommandTitle
            | MsgId::VscodeCommandRenamePrompt
            | MsgId::VscodeCommandRenamePlaceholder
            | MsgId::VscodeCommandRenameBusy
            | MsgId::VscodeCommandRenameDocumentRequired
            | MsgId::VscodeCommandRenameUnavailable
            | MsgId::VscodeCommandRenameInvalid
            | MsgId::VscodeCommandRenameStale
            | MsgId::VscodeCommandRenameApplyFailed
            | MsgId::VscodeCommandRenameRequestFailed
    };
}

pub(super) const fn clients(id: MsgId) -> &'static [Client] {
    match id {
        MsgId::WriterPreview
        | MsgId::WriterRestartPreview
        | MsgId::WriterClosePreview
        | MsgId::WriterContinue
        | MsgId::WriterTrue
        | MsgId::WriterFalse
        | MsgId::WriterConditionInput
        | MsgId::WriterConditionAnswer
        | MsgId::WriterAcknowledge
        | MsgId::WriterEffectFailed
        | MsgId::WriterPreviewTrace
        | MsgId::WriterPreviewStale
        | MsgId::WriterAwaitingEffect
        | MsgId::WriterSampleFailure
        | MsgId::WriterUnified
        | MsgId::WriterSideBySide
        | MsgId::WriterDraftVersion
        | MsgId::WriterDiskVersion
        | MsgId::WriterMissingVersion
        | MsgId::WriterWording
        | MsgId::WriterDefaultWording
        | MsgId::WriterPluralForm
        | MsgId::WriterPluralRule
        | MsgId::WriterEntryEditor
        | MsgId::WriterComparisonResolution
        | MsgId::WriterEntryPluralInvalid
        | MsgId::WriterExternalStructureChanged
        | MsgId::WriterTrialInputs
        | MsgId::WriterTrialInputsHelp
        | MsgId::WriterSourceOnly
        | MsgId::WriterIncludeDrafts
        | MsgId::WriterTrialInvalidValue
        | MsgId::WriterLookupMatched
        | MsgId::WriterLookupMissing
        | MsgId::WriterTrialEnded
        | MsgId::WriterTrialChoice
        | MsgId::WriterTrialDeferred
        | MsgId::WriterTrialEffect
        | MsgId::WriterCompleteSource
        | MsgId::WriterFilterCompletions
        | MsgId::WriterNoCompletions
        | MsgId::WriterReturnTranslation
        | MsgId::WriterTrialSaved
        | MsgId::WriterTrialDrafts
        | MsgId::WriterSourceRevision
        | MsgId::WriterApplyDraft
        | MsgId::WriterDiscardDraft
        | MsgId::WriterCompareReturn
        | MsgId::WriterRefresh
        | MsgId::WriterRefreshSave
        | MsgId::WriterRefreshAdded
        | MsgId::WriterRefreshChanged
        | MsgId::WriterRefreshRemoved
        | MsgId::WriterRefreshHelp
        | MsgId::WriterRefreshed
        | MsgId::WriterSourceUpdates
        | MsgId::WriterRefreshScope
        | MsgId::WriterRefreshScopeHelp
        | MsgId::WriterRefreshRecheck
        | MsgId::WriterRefreshDone
        | MsgId::WriterRefreshReview
        | MsgId::WriterRefreshNoChanges
        | MsgId::WriterNearbySource
        | MsgId::WriterPreviousSource
        | MsgId::WriterCurrentSource
        | MsgId::WriterTranslatorNotes
        | MsgId::WriterSourceChanged
        | MsgId::WriterChangeNew
        | MsgId::WriterChangeChanged
        | MsgId::WriterChangeRemoved
        | MsgId::WriterIncoming
        | MsgId::WriterSource
        | MsgId::WriterTranslation => &[Client::NativeGui],
        MsgId::WriterCompare
        | MsgId::WriterCompareHelp
        | MsgId::WriterKeepDrafts
        | MsgId::WriterUseFile
        | MsgId::WriterCompared => &[Client::NativeGui],
        MsgId::WriterWrite
        | MsgId::WriterLocalise
        | MsgId::WriterMatchingEntries
        | MsgId::WriterChooseLanguage
        | MsgId::WriterReadPassage
        | MsgId::WriterNoLanguages
        | MsgId::WriterUnavailablePassage
        | MsgId::WriterCofiLanguage
        | MsgId::WriterLocalisation
        | MsgId::WriterCatalogue
        | MsgId::WriterTranslationQueue
        | MsgId::WriterStartLocalisation
        | MsgId::WriterAddLanguage
        | MsgId::WriterTargetLanguage
        | MsgId::WriterLanguageExample
        | MsgId::WriterNewCataloguePath
        | MsgId::WriterCreateCatalogue
        | MsgId::WriterCancel
        | MsgId::WriterCreateProjectScope
        | MsgId::WriterCreateDocumentScope
        | MsgId::WriterCreateHelp
        | MsgId::WriterCreatingCatalogue
        | MsgId::WriterCatalogueCreated
        | MsgId::WriterInvalidLanguage
        | MsgId::WriterGettextMissing
        | MsgId::WriterCreationFailed
        | MsgId::WriterPluralUnknown
        | MsgId::WriterCatalogueExists
        | MsgId::WriterCreationChanged
        | MsgId::WriterCreateSourceDraft
        | MsgId::WriterPoExtension
        | MsgId::WriterCreateIncomplete
        | MsgId::WriterCreateEmpty
        | MsgId::WriterOptional
        | MsgId::WriterOpenCatalogue
        | MsgId::WriterNoEntry
        | MsgId::WriterUntranslated
        | MsgId::WriterReviewPending
        | MsgId::WriterReviewed
        | MsgId::WriterNeedsReview
        | MsgId::WriterSaved
        | MsgId::WriterUnsaved
        | MsgId::WriterTranslationSaved
        | MsgId::WriterPlaceholder
        | MsgId::WriterSave
        | MsgId::WriterDiscard
        | MsgId::WriterCataloguePath
        | MsgId::WriterFileWorkflow
        | MsgId::WriterReload
        | MsgId::WriterReloaded
        | MsgId::WriterClose
        | MsgId::WriterOpen
        | MsgId::WriterPoCatalogue
        | MsgId::WriterCloseDrafts
        | MsgId::WriterOpenDrafts
        | MsgId::WriterReloadDrafts
        | MsgId::WriterEmptyReview
        | MsgId::WriterQueueScope
        | MsgId::WriterSearch
        | MsgId::WriterAttention
        | MsgId::WriterNoMatches
        | MsgId::WriterPrevious
        | MsgId::WriterNext
        | MsgId::WriterRulesDestination
        | MsgId::WriterRulesGroup
        | MsgId::WriterRulesMatch
        | MsgId::WriterRulesAll
        | MsgId::WriterOpenDocuments
        | MsgId::WriterSaveCloseDocument
        | MsgId::WriterCloseDocumentDraft
        | MsgId::WriterShowContext
        | MsgId::WriterHideContext
        | MsgId::WriterNoChanges
        | MsgId::WriterAllChanges
        | MsgId::WriterChange
        | MsgId::WriterDeclarations
        | MsgId::WriterUnknownProducer
        | MsgId::WriterDeclarationCondition
        | MsgId::WriterDeclarationEffect
        | MsgId::WriterDeclarationSpeaker
        | MsgId::WriterDeclarationRegistry
        | MsgId::WriterDeclarationSourceDetails
        | MsgId::WriterBindSource
        | MsgId::WriterEditDeclarationSource
        | MsgId::WriterGenerateSchema
        | MsgId::WriterSchemaCurrent
        | MsgId::WriterSchemaStale
        | MsgId::WriterSchemaReadOnly
        | MsgId::WriterBrowseSchema
        | MsgId::WriterSourceSaved
        | MsgId::WriterBuildScenes
        | MsgId::WriterBuildSaved
        | MsgId::WriterSaveBuild
        | MsgId::WriterBuildAll
        | MsgId::WriterBuildScope
        | MsgId::WriterBuildInputs
        | MsgId::WriterBuilding
        | MsgId::WriterBuildCancelling
        | MsgId::WriterRenameProject
        | MsgId::WriterRenameReview
        | MsgId::WriterRenameApply
        | MsgId::WriterRenameHint
        | MsgId::WriterRenameName
        | MsgId::WriterRenameFrom
        | MsgId::WriterRenameApplied
        | MsgId::WriterDiskDraftHint
        | MsgId::WriterDiskChanged
        | MsgId::WriterExternalOpened
        | MsgId::WriterSaveExternal
        | MsgId::WriterCompareDisk
        | MsgId::WriterUseEditableDraft
        | MsgId::WriterReturnWriting
        | MsgId::WriterProposedSource
        | MsgId::WriterBackDeclarations
        | MsgId::WriterSearchDeclarations
        | MsgId::WriterChanges
        | MsgId::WriterLine
        | MsgId::WriterSaveProject
        | MsgId::WriterExternalOpening
        | MsgId::WriterCatalogueChanged
        | MsgId::WriterReloadSchemaSource
        | MsgId::WriterReloadProducer
        | MsgId::WriterProducerNotRegistered
        | MsgId::WriterGenerating
        | MsgId::WriterRegenerate
        | MsgId::WriterConfigureSourceEditor
        | MsgId::WriterOpenDeclarationSource
        | MsgId::WriterProducerFinished
        | MsgId::WriterReloadGenerated
        | MsgId::WriterRulesAny
        | MsgId::WriterGuiJobsPending
        | MsgId::WriterGuiAddBeat
        | MsgId::WriterGuiAddLine
        | MsgId::WriterGuiAddReply
        | MsgId::WriterGuiArrange
        | MsgId::WriterGuiArrangeAutomatically
        | MsgId::WriterGuiBeatIdentifierHint
        | MsgId::WriterGuiCancelOpening
        | MsgId::WriterGuiCancelRunningJobs
        | MsgId::WriterGuiChangeDestination
        | MsgId::WriterGuiChange
        | MsgId::WriterGuiCompleteCtrlSpace
        | MsgId::WriterGuiConfigurationFile
        | MsgId::WriterGuiConnections
        | MsgId::WriterGuiMapGestureHelp
        | MsgId::WriterGuiDismissMessage
        | MsgId::WriterGuiEditSource
        | MsgId::WriterGuiEndConversation
        | MsgId::WriterGuiFit
        | MsgId::WriterGuiHelp
        | MsgId::WriterGuiConnectionHelp
        | MsgId::WriterGuiKeepEditing
        | MsgId::WriterGuiKeepRecoveryCopyAndReloadDisk
        | MsgId::WriterGuiMapHelp
        | MsgId::WriterGuiNoMatchingSavedPassagesTryFewerWords
        | MsgId::WriterGuiNoMatchingScenesOrBeats
        | MsgId::WriterGuiNone
        | MsgId::WriterGuiOpenAProjectFirst
        | MsgId::WriterGuiOpenAProjectToEditItsSettings
        | MsgId::WriterGuiOpenProject
        | MsgId::WriterGuiOpenUnsavedTranslations
        | MsgId::WriterGuiPassageActions
        | MsgId::WriterGuiPreviewLimit
        | MsgId::WriterGuiProject
        | MsgId::WriterGuiProjectSettingsHint
        | MsgId::WriterGuiProjectSettings
        | MsgId::WriterGuiRefreshProjectContext
        | MsgId::WriterGuiReplies
        | MsgId::WriterGuiResetZoom
        | MsgId::WriterGuiSaveAllTranslationDrafts
        | MsgId::WriterGuiScenes
        | MsgId::WriterGuiShowMoreResults
        | MsgId::WriterGuiSourceReadOnly
        | MsgId::WriterGuiTargetIsOutsideThisScene
        | MsgId::WriterGuiTogglePinnedReference
        | MsgId::WriterGuiTryScene
        | MsgId::WriterGuiUnpinReference
        | MsgId::WriterGuiUserPreferences
        | MsgId::WriterGuiVimHelp
        | MsgId::WriterWorkspaceMenu
        | MsgId::WriterRulesActions
        | MsgId::WriterWorkspacePresentation
        | MsgId::WriterWorkspaceIncrease
        | MsgId::WriterWorkspaceDecrease
        | MsgId::WriterWorkspaceCloseCommands
        | MsgId::WriterWorkspaceNoCommandResults
        | MsgId::WriterWorkspaceGoToSearch
        | MsgId::WriterWorkspaceCommandSearch
        | MsgId::WriterWorkspaceCommandUnavailable
        | MsgId::WriterWorkspaceSaveAll
        | MsgId::WriterWorkspaceSave
        | MsgId::WriterWorkspaceRedo
        | MsgId::WriterWorkspaceUndo
        | MsgId::WriterWorkspaceOpenScript
        | MsgId::WriterWorkspaceResizeDrawer
        | MsgId::WriterWorkspaceResizeScript
        | MsgId::WriterWorkspaceUiScale
        | MsgId::WriterWorkspaceSourceSize
        | MsgId::WriterWorkspaceReadingSize
        | MsgId::WriterWorkspaceExitFocus
        | MsgId::WriterWorkspaceFocusWriting
        | MsgId::WriterWorkspaceGoTo
        | MsgId::WriterWorkspaceCommands
        | MsgId::WriterWorkspaceSplitView
        | MsgId::WriterWorkspaceWritingView
        | MsgId::WriterWorkspaceSourceView
        | MsgId::WriterWorkspaceMapView
        | MsgId::WriterWorkspaceScriptView
        | MsgId::WriterRulesTitle
        | MsgId::WriterRulesApply
        | MsgId::WriterRulesDiscard
        | MsgId::WriterRulesOpen
        | MsgId::WriterRulesReturn
        | MsgId::WriterRulesSource
        | MsgId::WriterRulesAvailability
        | MsgId::WriterRulesAlways
        | MsgId::WriterRulesMakeAlways
        | MsgId::WriterRulesChosen
        | MsgId::WriterRulesNoEffects
        | MsgId::WriterRulesPreserved
        | MsgId::WriterRulesSourceChanged
        | MsgId::WriterRulesNegate
        | MsgId::WriterRulesRemoveNegation
        | MsgId::WriterRulesDelivery
        | MsgId::WriterRulesRemove
        | MsgId::WriterRulesImmediate
        | MsgId::WriterRulesBlocking
        | MsgId::WriterRulesDeferred
        | MsgId::WriterRulesSearchValues
        | MsgId::WriterRulesChooseValue
        | MsgId::WriterRulesNoValues
        | MsgId::WriterRulesAddEffect
        | MsgId::WriterRulesAddCondition
        | MsgId::WriterRulesChooseDeclaration
        | MsgId::WriterRulesNoDeclarations => &[Client::NativeGui],
        tui_message_ids!() => &[Client::Tui],
        vscode_command_message_ids!() => &[Client::VsCode, Client::VsCodium],
        MsgId::LspClientDisplayName | MsgId::LspClientRestartExhausted => &[
            Client::Lsp,
            Client::VsCode,
            Client::VsCodium,
            Client::Neovim,
        ],
        neovim_message_ids!() => &[Client::Neovim],
        lsp_client_message_ids!() => &[Client::Lsp, Client::VsCode, Client::VsCodium],
        lsp_message_ids!() => &[Client::Lsp],
        cli_message_ids!() => &[Client::Cli],
    }
}
