[package]
name = "recite-bakeoff-gtk"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
gtk = { package = "gtk4", version = "=0.11.4", features = ["v4_22"] }
recite-bakeoff-authoring.workspace = true
recite-bakeoff-grammar = { path = "../grammar" }
tree-sitter = "0.26"

[lints]
workspace = true
