[workspace]

[package]
name = "recite-zed"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Recite language support for Zed"
repository = "https://github.com/plethu/recite"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"

[lints.rust]
unsafe_code = "forbid"
unreachable_pub = "warn"

[lints.clippy]
unwrap_used = "warn"
expect_used = "warn"
todo = "warn"
unimplemented = "warn"
