[workspace]
members = [
    "crates/recite-cli",
    "crates/recite-compiler",
    "crates/recite-core",
    "crates/recite-lsp",
    "crates/recite-parser",
    "crates/recite-runtime",
]
resolver = "3"

[workspace.package]
version = "0.0.1"
edition = "2024"
license = "MIT"
repository = "https://codeberg.org/plethu/recite"
readme = "README.md"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.dependencies]
recite-core = { version = "0.0.1", path = "crates/recite-core" }
recite-parser = { version = "0.0.1", path = "crates/recite-parser" }
recite-compiler = { version = "0.0.1", path = "crates/recite-compiler" }
recite-runtime = { version = "0.0.1", path = "crates/recite-runtime" }
blake3 = "1.8.5"
clap = { version = "4.5.51", features = ["derive"] }
insta = { version = "1.47.2", default-features = false }
rmp-serde = "1.3.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_bytes = "0.11.19"
serde-value = "0.7.0"
serde_json = "1.0.149"
tempfile = "3.23.0"
