-- Generated from the canonical diagnostic contracts and diagnostics.ftl.
-- Do not edit; run diagnostic-projections.mjs --update.
return {
  ["diagnostic-config-101"] = { arguments = { { name = "detail", type = "string" } }, template = "project manifest not found: {$detail}" },
  ["diagnostic-config-102"] = { arguments = { { name = "detail", type = "string" } }, template = "could not read project manifest: {$detail}" },
  ["diagnostic-config-103"] = { arguments = { { name = "detail", type = "string" } }, template = "malformed project manifest: {$detail}" },
  ["diagnostic-config-104"] = { arguments = { { name = "detail", type = "string" } }, template = "unsupported project manifest version: {$detail}" },
  ["diagnostic-config-105"] = { arguments = { { name = "detail", type = "string" } }, template = "invalid project source root: {$detail}" },
  ["diagnostic-config-106"] = { arguments = { { name = "detail", type = "string" } }, template = "invalid project exclusion: {$detail}" },
  ["diagnostic-config-107"] = { arguments = { { name = "detail", type = "string" } }, template = "project source root is missing: {$detail}" },
  ["diagnostic-config-108"] = { arguments = { { name = "detail", type = "string" } }, template = "could not read project source root: {$detail}" },
  ["diagnostic-config-109"] = { arguments = { { name = "detail", type = "string" } }, template = "project source root escapes the project: {$detail}" },
  ["diagnostic-config-110"] = { arguments = { { name = "detail", type = "string" } }, template = "duplicate project source root: {$detail}" },
  ["diagnostic-config-111"] = { arguments = { { name = "detail", type = "string" } }, template = "overlapping project source root: {$detail}" },
  ["diagnostic-config-112"] = { arguments = { { name = "detail", type = "string" } }, template = "could not read project source directory: {$detail}" },
  ["diagnostic-config-113"] = { arguments = { { name = "detail", type = "string" } }, template = "project discovery encountered a non-UTF-8 path: {$detail}" },
  ["diagnostic-config-114"] = { arguments = { { name = "detail", type = "string" } }, template = "project source symlink escapes the project: {$detail}" },
  ["diagnostic-config-115"] = { arguments = { { name = "detail", type = "string" } }, template = "project source is not valid UTF-8: {$detail}" },
  ["diagnostic-config-116"] = { arguments = { { name = "detail", type = "string" } }, template = "project source root is not a directory: {$detail}" },
  ["diagnostic-config-117"] = { arguments = { { name = "detail", type = "string" } }, template = "project source has an invalid document key: {$detail}" },
  ["diagnostic-fresh-001"] = { arguments = { { name = "asset", type = "string" }, { name = "source", type = "string" } }, template = "compiled asset '{$asset}' is stale for source '{$source}'" },
  ["diagnostic-fresh-001-cause-001"] = { arguments = {  } },
  ["diagnostic-fresh-001-meaning"] = { arguments = {  } },
  ["diagnostic-fresh-001-remediation-001"] = { arguments = {  } },
  ["diagnostic-fresh-002"] = { arguments = { { name = "asset", type = "string" } }, template = "compiled asset '{$asset}' has a stale schema fingerprint" },
  ["diagnostic-fresh-002-cause-001"] = { arguments = {  } },
  ["diagnostic-fresh-002-meaning"] = { arguments = {  } },
  ["diagnostic-fresh-002-remediation-001"] = { arguments = {  } },
  ["diagnostic-fresh-003"] = { arguments = { { name = "asset", type = "string" }, { name = "expected", type = "integer" }, { name = "version", type = "integer" } }, template = "compiled asset '{$asset}' uses compiler compatibility version {$version}, expected {$expected}" },
  ["diagnostic-fresh-003-cause-001"] = { arguments = {  } },
  ["diagnostic-fresh-003-meaning"] = { arguments = {  } },
  ["diagnostic-fresh-003-remediation-001"] = { arguments = {  } },
  ["diagnostic-id-001"] = { arguments = {  }, template = "line header must include a stable line id" },
  ["diagnostic-id-001-cause-001"] = { arguments = {  } },
  ["diagnostic-id-001-help"] = { arguments = {  } },
  ["diagnostic-id-001-meaning"] = { arguments = {  } },
  ["diagnostic-id-001-remediation-001"] = { arguments = {  } },
  ["diagnostic-id-002"] = { arguments = {  }, template = "choice header must include a stable choice id" },
  ["diagnostic-id-002-cause-001"] = { arguments = {  } },
  ["diagnostic-id-002-help"] = { arguments = {  } },
  ["diagnostic-id-002-meaning"] = { arguments = {  } },
  ["diagnostic-id-002-remediation-001"] = { arguments = {  } },
  ["diagnostic-id-003"] = { arguments = { { name = "id", type = "string" } }, template = "duplicate localisable id `{$id}` on line" },
  ["diagnostic-id-003-cause-001"] = { arguments = {  } },
  ["diagnostic-id-003-help"] = { arguments = {  } },
  ["diagnostic-id-003-meaning"] = { arguments = {  } },
  ["diagnostic-id-003-related"] = { arguments = {  } },
  ["diagnostic-id-003-remediation-001"] = { arguments = {  } },
  ["diagnostic-id-004"] = { arguments = { { name = "id", type = "string" } }, template = "duplicate localisable id `{$id}` on choice" },
  ["diagnostic-id-004-cause-001"] = { arguments = {  } },
  ["diagnostic-id-004-help"] = { arguments = {  } },
  ["diagnostic-id-004-meaning"] = { arguments = {  } },
  ["diagnostic-id-004-related"] = { arguments = {  } },
  ["diagnostic-id-004-remediation-001"] = { arguments = {  } },
  ["diagnostic-id-005"] = { arguments = {  }, template = "line header has an unfrozen draft source id" },
  ["diagnostic-id-005-cause-001"] = { arguments = {  } },
  ["diagnostic-id-005-help"] = { arguments = {  } },
  ["diagnostic-id-005-meaning"] = { arguments = {  } },
  ["diagnostic-id-005-remediation-001"] = { arguments = {  } },
  ["diagnostic-id-006"] = { arguments = {  }, template = "choice header has an unfrozen draft source id" },
  ["diagnostic-id-006-cause-001"] = { arguments = {  } },
  ["diagnostic-id-006-help"] = { arguments = {  } },
  ["diagnostic-id-006-meaning"] = { arguments = {  } },
  ["diagnostic-id-006-remediation-001"] = { arguments = {  } },
  ["diagnostic-id-007"] = { arguments = { { name = "id", type = "string" } }, template = "line header has malformed source id `{$id}`" },
  ["diagnostic-id-007-cause-001"] = { arguments = {  } },
  ["diagnostic-id-007-help"] = { arguments = {  } },
  ["diagnostic-id-007-meaning"] = { arguments = {  } },
  ["diagnostic-id-007-remediation-001"] = { arguments = {  } },
  ["diagnostic-id-008"] = { arguments = { { name = "id", type = "string" } }, template = "choice header has malformed source id `{$id}`" },
  ["diagnostic-id-008-cause-001"] = { arguments = {  } },
  ["diagnostic-id-008-help"] = { arguments = {  } },
  ["diagnostic-id-008-meaning"] = { arguments = {  } },
  ["diagnostic-id-008-remediation-001"] = { arguments = {  } },
  ["diagnostic-id-034"] = { arguments = { { name = "context", type = "string" } }, template = "invalid stable PO context `{$context}`" },
  ["diagnostic-id-034-cause-001"] = { arguments = {  } },
  ["diagnostic-id-034-meaning"] = { arguments = {  } },
  ["diagnostic-id-034-remediation-001"] = { arguments = {  } },
  ["diagnostic-id-035"] = { arguments = { { name = "context", type = "string" }, { name = "source_text", type = "string" } }, template = "duplicate PO catalogue key: context `{$context}` and msgid `{$source_text}`" },
  ["diagnostic-id-035-cause-001"] = { arguments = {  } },
  ["diagnostic-id-035-meaning"] = { arguments = {  } },
  ["diagnostic-id-035-remediation-001"] = { arguments = {  } },
  ["diagnostic-legacy-message"] = { arguments = { { name = "message", type = "string" } }, template = "{$message}" },
  ["diagnostic-parse-001"] = { arguments = {  }, template = "expected a Recite statement header or indented prose" },
  ["diagnostic-parse-001-cause-001"] = { arguments = {  } },
  ["diagnostic-parse-001-meaning"] = { arguments = {  } },
  ["diagnostic-parse-001-remediation-001"] = { arguments = {  } },
  ["diagnostic-parse-002"] = { arguments = {  }, template = "statement appears before a block header" },
  ["diagnostic-parse-002-cause-001"] = { arguments = {  } },
  ["diagnostic-parse-002-meaning"] = { arguments = {  } },
  ["diagnostic-parse-002-remediation-001"] = { arguments = {  } },
  ["diagnostic-parse-003"] = { arguments = {  }, template = "block header must include a block id" },
  ["diagnostic-parse-003-cause-001"] = { arguments = {  } },
  ["diagnostic-parse-003-meaning"] = { arguments = {  } },
  ["diagnostic-parse-003-remediation-001"] = { arguments = {  } },
  ["diagnostic-parse-005"] = { arguments = {  }, template = "block id must not be empty" },
  ["diagnostic-parse-005-cause-001"] = { arguments = {  } },
  ["diagnostic-parse-005-meaning"] = { arguments = {  } },
  ["diagnostic-parse-005-remediation-001"] = { arguments = {  } },
  ["diagnostic-parse-007"] = { arguments = {  }, template = "mixed indentation inside statement body" },
  ["diagnostic-parse-007-cause-001"] = { arguments = {  } },
  ["diagnostic-parse-007-meaning"] = { arguments = {  } },
  ["diagnostic-parse-007-remediation-001"] = { arguments = {  } },
  ["diagnostic-parse-008"] = { arguments = {  }, template = "malformed statement header field" },
  ["diagnostic-parse-008-cause-001"] = { arguments = {  } },
  ["diagnostic-parse-008-meaning"] = { arguments = {  } },
  ["diagnostic-parse-008-remediation-001"] = { arguments = {  } },
  ["diagnostic-parse-010"] = { arguments = {  }, template = "divert header must include a target" },
  ["diagnostic-parse-010-cause-001"] = { arguments = {  } },
  ["diagnostic-parse-010-meaning"] = { arguments = {  } },
  ["diagnostic-parse-010-remediation-001"] = { arguments = {  } },
  ["diagnostic-parse-011"] = { arguments = {  }, template = "malformed divert target" },
  ["diagnostic-parse-011-cause-001"] = { arguments = {  } },
  ["diagnostic-parse-011-meaning"] = { arguments = {  } },
  ["diagnostic-parse-011-remediation-001"] = { arguments = {  } },
  ["diagnostic-parse-012"] = { arguments = { { name = "reason", type = "string" } } },
  ["diagnostic-parse-012-cause-001"] = { arguments = {  } },
  ["diagnostic-parse-012-meaning"] = { arguments = {  } },
  ["diagnostic-parse-012-remediation-001"] = { arguments = {  } },
  ["diagnostic-parse-012-unexpected-character"] = { arguments = { { name = "character", type = "string" } }, template = "malformed effect statement: unexpected character '{$character}'" },
  ["diagnostic-parse-013"] = { arguments = { { name = "reason", type = "string" } } },
  ["diagnostic-parse-013-cause-001"] = { arguments = {  } },
  ["diagnostic-parse-013-meaning"] = { arguments = {  } },
  ["diagnostic-parse-013-remediation-001"] = { arguments = {  } },
  ["diagnostic-parse-013-unexpected-character"] = { arguments = { { name = "character", type = "string" } }, template = "malformed condition expression: unexpected character '{$character}'" },
  ["diagnostic-parse-014"] = { arguments = {  }, template = "case header must include a variant or _" },
  ["diagnostic-parse-014-cause-001"] = { arguments = {  } },
  ["diagnostic-parse-014-meaning"] = { arguments = {  } },
  ["diagnostic-parse-014-remediation-001"] = { arguments = {  } },
  ["diagnostic-parse-015"] = { arguments = {  }, template = ":else must immediately follow a sibling :if body" },
  ["diagnostic-parse-015-cause-001"] = { arguments = {  } },
  ["diagnostic-parse-015-meaning"] = { arguments = {  } },
  ["diagnostic-parse-015-remediation-001"] = { arguments = {  } },
  ["diagnostic-parse-016"] = { arguments = {  }, template = ":case must appear inside a :match body" },
  ["diagnostic-parse-016-cause-001"] = { arguments = {  } },
  ["diagnostic-parse-016-meaning"] = { arguments = {  } },
  ["diagnostic-parse-016-remediation-001"] = { arguments = {  } },
  ["diagnostic-parse-017"] = { arguments = {  }, template = "prose cannot follow nested statements in the same body" },
  ["diagnostic-parse-017-cause-001"] = { arguments = {  } },
  ["diagnostic-parse-017-meaning"] = { arguments = {  } },
  ["diagnostic-parse-017-remediation-001"] = { arguments = {  } },
  ["diagnostic-parse-018"] = { arguments = {  }, template = "old trailing choice if syntax is not valid Recite v1 syntax" },
  ["diagnostic-parse-018-cause-001"] = { arguments = {  } },
  ["diagnostic-parse-018-meaning"] = { arguments = {  } },
  ["diagnostic-parse-018-remediation-001"] = { arguments = {  } },
  ["diagnostic-parse-034-cause-001"] = { arguments = {  } },
  ["diagnostic-parse-034-duplicate-field"] = { arguments = { { name = "field", type = "string" } }, template = "duplicate PO field {$field}" },
  ["diagnostic-parse-034-expected-directive"] = { arguments = {  }, template = "expected PO directive" },
  ["diagnostic-parse-034-expected-quoted-string"] = { arguments = {  }, template = "expected quoted PO string" },
  ["diagnostic-parse-034-invalid-field-order"] = { arguments = { { name = "value", type = "string" } }, template = "invalid PO field order: {$value}" },
  ["diagnostic-parse-034-meaning"] = { arguments = {  } },
  ["diagnostic-parse-034-missing-field"] = { arguments = { { name = "field", type = "string" } }, template = "entry is missing {$field}" },
  ["diagnostic-parse-034-quoted-without-field"] = { arguments = {  }, template = "quoted continuation without a PO field" },
  ["diagnostic-parse-034-remediation-001"] = { arguments = {  } },
  ["diagnostic-parse-034-unexpected-trailing-text"] = { arguments = {  }, template = "unexpected text after quoted PO string" },
  ["diagnostic-parse-034-unsupported-escape"] = { arguments = { { name = "escape", type = "string" } }, template = "unsupported PO escape {$escape}" },
  ["diagnostic-parse-034-unterminated-quoted-string"] = { arguments = {  }, template = "unterminated quoted PO string" },
  ["diagnostic-project-001"] = { arguments = { { name = "detail", type = "string" } }, template = "malformed project manifest: {$detail}" },
  ["diagnostic-project-001-cause-001"] = { arguments = {  } },
  ["diagnostic-project-001-meaning"] = { arguments = {  } },
  ["diagnostic-project-001-remediation-001"] = { arguments = {  } },
  ["diagnostic-project-002"] = { arguments = { { name = "scene_id", type = "string" } }, template = "duplicate scene id '{$scene_id}'" },
  ["diagnostic-project-002-cause-001"] = { arguments = {  } },
  ["diagnostic-project-002-meaning"] = { arguments = {  } },
  ["diagnostic-project-002-related"] = { arguments = {  } },
  ["diagnostic-project-002-remediation-001"] = { arguments = {  } },
  ["diagnostic-project-003"] = { arguments = { { name = "asset", type = "string" }, { name = "scene_id", type = "string" } }, template = "scene '{$scene_id}' references missing compiled asset '{$asset}'" },
  ["diagnostic-project-003-cause-001"] = { arguments = {  } },
  ["diagnostic-project-003-meaning"] = { arguments = {  } },
  ["diagnostic-project-003-remediation-001"] = { arguments = {  } },
  ["diagnostic-project-004"] = { arguments = { { name = "block", type = "string" }, { name = "scene_id", type = "string" } }, template = "scene '{$scene_id}' references unknown block '{$block}'" },
  ["diagnostic-project-004-cause-001"] = { arguments = {  } },
  ["diagnostic-project-004-meaning"] = { arguments = {  } },
  ["diagnostic-project-004-remediation-001"] = { arguments = {  } },
  ["diagnostic-project-005"] = { arguments = { { name = "scene_id", type = "string" } }, template = "scene '{$scene_id}' must declare at least one participant" },
  ["diagnostic-project-005-cause-001"] = { arguments = {  } },
  ["diagnostic-project-005-meaning"] = { arguments = {  } },
  ["diagnostic-project-005-remediation-001"] = { arguments = {  } },
  ["diagnostic-project-006"] = { arguments = { { name = "asset", type = "string" }, { name = "source", type = "string" } }, template = "compiled asset '{$asset}' references missing source '{$source}'" },
  ["diagnostic-project-006-cause-001"] = { arguments = {  } },
  ["diagnostic-project-006-meaning"] = { arguments = {  } },
  ["diagnostic-project-006-remediation-001"] = { arguments = {  } },
  ["diagnostic-project-007"] = { arguments = { { name = "asset", type = "string" }, { name = "version", type = "integer" } }, template = "compiled asset '{$asset}' uses unsupported format version {$version}" },
  ["diagnostic-project-007-cause-001"] = { arguments = {  } },
  ["diagnostic-project-007-malformed"] = { arguments = { { name = "asset", type = "string" }, { name = "detail", type = "string" }, { name = "scene_id", type = "string" } }, template = "scene '{$scene_id}' references malformed compiled asset '{$asset}': {$detail}" },
  ["diagnostic-project-007-meaning"] = { arguments = {  } },
  ["diagnostic-project-007-remediation-001"] = { arguments = {  } },
  ["diagnostic-project-008"] = { arguments = { { name = "participant", type = "string" }, { name = "scene_id", type = "string" } }, template = "scene '{$scene_id}' references unknown participant '{$participant}'" },
  ["diagnostic-project-008-cause-001"] = { arguments = {  } },
  ["diagnostic-project-008-compiled-asset"] = { arguments = { { name = "asset", type = "string" }, { name = "participant", type = "string" }, { name = "scene_id", type = "string" } }, template = "scene '{$scene_id}' participant '{$participant}' is not present in compiled asset '{$asset}'" },
  ["diagnostic-project-008-meaning"] = { arguments = {  } },
  ["diagnostic-project-008-remediation-001"] = { arguments = {  } },
  ["diagnostic-schema-001-availability-binding-int"] = { arguments = { { name = "argument", type = "string" }, { name = "condition", type = "string" } }, template = "condition '{$condition}' availability_reason argument '{$argument}' expects int, but got non-integer number" },
  ["diagnostic-schema-001-availability-binding-literal-type"] = { arguments = { { name = "actual", type = "string" }, { name = "argument", type = "string" }, { name = "condition", type = "string" }, { name = "expected", type = "string" } }, template = "condition '{$condition}' availability_reason argument '{$argument}' expects {$expected}, but got {$actual} literal" },
  ["diagnostic-schema-001-availability-binding-missing-name"] = { arguments = {  }, template = "availability reason binding must contain name" },
  ["diagnostic-schema-001-availability-binding-string-type"] = { arguments = { { name = "argument", type = "string" }, { name = "condition", type = "string" }, { name = "expected", type = "string" } }, template = "condition '{$condition}' availability_reason argument '{$argument}' expects {$expected}, but got string literal" },
  ["diagnostic-schema-001-availability-binding-type-mismatch"] = { arguments = { { name = "actual", type = "string" }, { name = "argument", type = "string" }, { name = "condition", type = "string" }, { name = "condition_param", type = "string" }, { name = "expected", type = "string" } }, template = "condition '{$condition}' availability_reason argument '{$argument}' expects {$expected}, but condition parameter '{$condition_param}' has {$actual}" },
  ["diagnostic-schema-001-availability-binding-unknown-value"] = { arguments = { { name = "argument", type = "string" }, { name = "condition", type = "string" }, { name = "expected", type = "string" }, { name = "value", type = "string" } }, template = "condition '{$condition}' availability_reason argument '{$argument}' uses unknown {$expected} value '{$value}'" },
  ["diagnostic-schema-001-availability-literal-missing-value"] = { arguments = {  }, template = "availability reason literal must contain value" },
  ["diagnostic-schema-001-availability-missing-reason-arg"] = { arguments = { { name = "argument", type = "string" }, { name = "condition", type = "string" } }, template = "condition '{$condition}' availability_reason is missing argument '{$argument}'" },
  ["diagnostic-schema-001-availability-non-bool-mapping"] = { arguments = { { name = "condition", type = "string" } }, template = "condition '{$condition}' availability_reason mapping is only allowed on bool-returning conditions" },
  ["diagnostic-schema-001-availability-tag-kind"] = { arguments = { { name = "kind", type = "string" } }, template = "unsupported availability reason argument kind '{$kind}'" },
  ["diagnostic-schema-001-availability-tag-missing-kind"] = { arguments = {  }, template = "availability reason argument tag must contain kind" },
  ["diagnostic-schema-001-availability-tagged-only-toml"] = { arguments = {  }, template = "tagged availability reason arguments are only supported in TOML" },
  ["diagnostic-schema-001-availability-template-invalid-name"] = { arguments = { { name = "name", type = "string" }, { name = "reason", type = "string" } }, template = "availability reason '{$reason}' template has invalid placeholder syntax: invalid placeholder name '{$name}'" },
  ["diagnostic-schema-001-availability-template-unescaped-closing-brace"] = { arguments = { { name = "reason", type = "string" } }, template = "availability reason '{$reason}' template has invalid placeholder syntax: unescaped closing brace" },
  ["diagnostic-schema-001-availability-template-unknown-param"] = { arguments = { { name = "placeholder", type = "string" }, { name = "reason", type = "string" } }, template = "availability reason '{$reason}' template references unknown parameter '{$placeholder}'" },
  ["diagnostic-schema-001-availability-template-unterminated"] = { arguments = { { name = "reason", type = "string" } }, template = "availability reason '{$reason}' template has invalid placeholder syntax: unterminated placeholder" },
  ["diagnostic-schema-001-availability-template-unused-param"] = { arguments = { { name = "parameter", type = "string" }, { name = "reason", type = "string" } }, template = "availability reason '{$reason}' parameter '{$parameter}' is not used in its template" },
  ["diagnostic-schema-001-availability-unknown-reason-param"] = { arguments = { { name = "argument", type = "string" }, { name = "condition", type = "string" } }, template = "condition '{$condition}' availability_reason binds unknown reason parameter '{$argument}'" },
  ["diagnostic-schema-001-cause-001"] = { arguments = {  } },
  ["diagnostic-schema-001-context-origin-name"] = { arguments = { { name = "owner", type = "string" } }, template = "{$owner} provenance context must be an identifier-like name" },
  ["diagnostic-schema-001-context-origins"] = { arguments = { { name = "owner", type = "string" } }, template = "{$owner} context_origins must map contexts to origins" },
  ["diagnostic-schema-001-contextual-value-origins"] = { arguments = { { name = "owner", type = "string" } }, template = "{$owner} contextual value_origins must map contexts to values" },
  ["diagnostic-schema-001-domain-context-values"] = { arguments = { { name = "domain", type = "string" } }, template = "metadata domain '{$domain}' requires values_by_context" },
  ["diagnostic-schema-001-domain-fallback-domain"] = { arguments = { { name = "domain", type = "string" } }, template = "metadata domain '{$domain}' fallback policy requires domain" },
  ["diagnostic-schema-001-domain-kind"] = { arguments = { { name = "domain", type = "string" }, { name = "kind", type = "string" } }, template = "metadata domain '{$domain}' uses unsupported kind '{$kind}'" },
  ["diagnostic-schema-001-domain-kind-field"] = { arguments = { { name = "domain", type = "string" }, { name = "field", type = "string" }, { name = "kind", type = "string" } }, template = "metadata domain '{$domain}' does not allow '{$field}' for kind '{$kind}'" },
  ["diagnostic-schema-001-domain-missing-context"] = { arguments = { { name = "domain", type = "string" } }, template = "metadata domain '{$domain}' requires explicit missing_context in generated JSON" },
  ["diagnostic-schema-001-domain-policy"] = { arguments = { { name = "domain", type = "string" }, { name = "policy", type = "string" } }, template = "metadata domain '{$domain}' uses unsupported missing_context policy '{$policy}'" },
  ["diagnostic-schema-001-domain-policy-domain"] = { arguments = { { name = "domain", type = "string" }, { name = "policy", type = "string" } }, template = "metadata domain '{$domain}' {$policy} policy must not declare domain" },
  ["diagnostic-schema-001-domain-selector"] = { arguments = { { name = "domain", type = "string" }, { name = "selector", type = "string" } }, template = "metadata domain '{$domain}' uses unsupported selector '{$selector}'" },
  ["diagnostic-schema-001-domain-selector-required"] = { arguments = { { name = "domain", type = "string" } }, template = "metadata domain '{$domain}' requires selector" },
  ["diagnostic-schema-001-domain-values"] = { arguments = { { name = "domain", type = "string" } }, template = "metadata domain '{$domain}' requires values" },
  ["diagnostic-schema-001-effect-mode"] = { arguments = { { name = "effect", type = "string" }, { name = "mode", type = "string" } }, template = "effect '{$effect}' uses unsupported mode '{$mode}'" },
  ["diagnostic-schema-001-empty-value"] = { arguments = { { name = "field", type = "string" } }, template = "{$field} must not be empty" },
  ["diagnostic-schema-001-flat-value-origins"] = { arguments = { { name = "owner", type = "string" } }, template = "{$owner} flat value_origins must map values to origins" },
  ["diagnostic-schema-001-float-not-representable"] = { arguments = { { name = "owner", type = "string" } }, template = "{$owner} must be finite and representable as f64" },
  ["diagnostic-schema-001-invalid-name"] = { arguments = { { name = "field", type = "string" } }, template = "{$field} must be an identifier-like schema name" },
  ["diagnostic-schema-001-json-parse"] = { arguments = { { name = "detail", type = "string" } }, template = "malformed schema manifest: {$detail}" },
  ["diagnostic-schema-001-label-placeholder-invalid-name"] = { arguments = { { name = "name", type = "string" }, { name = "output", type = "string" }, { name = "projector", type = "string" }, { name = "template_id", type = "string" } }, template = "projector '{$projector}' output '{$output}' presentation label '{$template_id}' has invalid placeholder syntax: invalid placeholder name '{$name}'" },
  ["diagnostic-schema-001-label-placeholder-unescaped-closing-brace"] = { arguments = { { name = "output", type = "string" }, { name = "projector", type = "string" }, { name = "template_id", type = "string" } }, template = "projector '{$projector}' output '{$output}' presentation label '{$template_id}' has invalid placeholder syntax: unescaped closing brace" },
  ["diagnostic-schema-001-label-placeholder-unterminated"] = { arguments = { { name = "output", type = "string" }, { name = "projector", type = "string" }, { name = "template_id", type = "string" } }, template = "projector '{$projector}' output '{$output}' presentation label '{$template_id}' has invalid placeholder syntax: unterminated placeholder" },
  ["diagnostic-schema-001-label-unknown-arg"] = { arguments = { { name = "output", type = "string" }, { name = "placeholder", type = "string" }, { name = "projector", type = "string" }, { name = "template_id", type = "string" } }, template = "projector '{$projector}' output '{$output}' presentation label '{$template_id}' references unknown argument '{$placeholder}'" },
  ["diagnostic-schema-001-label-unused-arg"] = { arguments = { { name = "arg", type = "string" }, { name = "output", type = "string" }, { name = "projector", type = "string" }, { name = "template_id", type = "string" } }, template = "projector '{$projector}' output '{$output}' presentation label '{$template_id}' argument '{$arg}' is not used in its template" },
  ["diagnostic-schema-001-meaning"] = { arguments = {  } },
  ["diagnostic-schema-001-metadata-array-type"] = { arguments = { { name = "metadata", type = "string" }, { name = "type_ref", type = "string" } }, template = "metadata '{$metadata}' uses projection-only array type '{$type_ref}'" },
  ["diagnostic-schema-001-metadata-domain-type"] = { arguments = { { name = "metadata", type = "string" }, { name = "type_ref", type = "string" } }, template = "metadata '{$metadata}' uses a metadata domain but has non-symbol type '{$type_ref}'" },
  ["diagnostic-schema-001-metadata-target"] = { arguments = { { name = "metadata", type = "string" }, { name = "target", type = "string" } }, template = "metadata '{$metadata}' uses unsupported target '{$target}'" },
  ["diagnostic-schema-001-origin-extension"] = { arguments = { { name = "key", type = "string" }, { name = "owner", type = "string" } }, template = "{$owner} origin extension '{$key}' must be namespaced" },
  ["diagnostic-schema-001-producer-content-fingerprint-blake3-digest-length"] = { arguments = { { name = "actual", type = "integer" } }, template = "manifest content_fingerprint is invalid: blake3 fingerprint digest must be 32 bytes, got {$actual}" },
  ["diagnostic-schema-001-producer-content-fingerprint-blake3-hex-data"] = { arguments = {  }, template = "manifest content_fingerprint is invalid: blake3 producer fingerprint must be hex" },
  ["diagnostic-schema-001-producer-content-fingerprint-blake3-hex-shape"] = { arguments = {  }, template = "manifest content_fingerprint is invalid: blake3 producer fingerprint must be even-length hex" },
  ["diagnostic-schema-001-producer-content-fingerprint-empty-algorithm"] = { arguments = {  }, template = "manifest content_fingerprint is invalid: FingerprintAlgorithm must not be empty" },
  ["diagnostic-schema-001-producer-content-fingerprint-empty-digest"] = { arguments = {  }, template = "manifest content_fingerprint is invalid: FingerprintDigest must not be empty" },
  ["diagnostic-schema-001-producer-export-version"] = { arguments = {  }, template = "schema_export_version must be greater than zero" },
  ["diagnostic-schema-001-projection-candidate-no-target"] = { arguments = { { name = "input", type = "string" }, { name = "projector", type = "string" } }, template = "projector '{$projector}' input '{$input}' reads candidate metadata but its selector has no metadata target" },
  ["diagnostic-schema-001-projection-candidate-source"] = { arguments = { { name = "input", type = "string" }, { name = "projector", type = "string" } }, template = "projector '{$projector}' input '{$input}' uses an incompatible candidate id source" },
  ["diagnostic-schema-001-projection-candidate-type-mismatch"] = { arguments = { { name = "actual", type = "string" }, { name = "expected", type = "string" }, { name = "input", type = "string" }, { name = "key", type = "string" }, { name = "projector", type = "string" } }, template = "projector '{$projector}' input '{$input}' expects {$expected}, but metadata key '{$key}' has {$actual}" },
  ["diagnostic-schema-001-projection-literal-int"] = { arguments = { { name = "owner", type = "string" } }, template = "{$owner} expects int, but got non-integer number" },
  ["diagnostic-schema-001-projection-literal-type"] = { arguments = { { name = "actual", type = "string" }, { name = "expected", type = "string" }, { name = "owner", type = "string" } }, template = "{$owner} expects {$expected}, but got {$actual} literal" },
  ["diagnostic-schema-001-projection-literal-unknown"] = { arguments = { { name = "expected", type = "string" }, { name = "owner", type = "string" }, { name = "value", type = "string" } }, template = "{$owner} uses unknown {$expected} value '{$value}'" },
  ["diagnostic-schema-001-projection-metadata-target"] = { arguments = { { name = "key", type = "string" }, { name = "projector", type = "string" }, { name = "target", type = "string" } }, template = "projector '{$projector}' references metadata key '{$key}' on unsupported target '{$target}'" },
  ["diagnostic-schema-001-projection-occurrence"] = { arguments = { { name = "input", type = "string" }, { name = "name", type = "string" }, { name = "projector", type = "string" } }, template = "projector '{$projector}' input '{$input}' uses unsupported metadata occurrence '{$name}'" },
  ["diagnostic-schema-001-projection-occurrence-all-type"] = { arguments = { { name = "input", type = "string" }, { name = "projector", type = "string" }, { name = "type_ref", type = "string" } }, template = "projector '{$projector}' input '{$input}' uses occurrence 'all' but has non-array type {$type_ref}" },
  ["diagnostic-schema-001-projection-occurrence-array"] = { arguments = { { name = "input", type = "string" }, { name = "projector", type = "string" }, { name = "type_ref", type = "string" } }, template = "projector '{$projector}' input '{$input}' uses array type {$type_ref} without occurrence 'all'" },
  ["diagnostic-schema-001-projection-occurrence-repeat"] = { arguments = { { name = "input", type = "string" }, { name = "key", type = "string" }, { name = "occurrence", type = "string" }, { name = "projector", type = "string" } }, template = "projector '{$projector}' input '{$input}' uses repeated occurrence '{$occurrence}' for non-repeatable metadata key '{$key}'" },
  ["diagnostic-schema-001-projection-output-target"] = { arguments = { { name = "output", type = "string" }, { name = "projector", type = "string" }, { name = "target", type = "string" } }, template = "projector '{$projector}' output '{$output}' uses unsupported target '{$target}'" },
  ["diagnostic-schema-001-projection-reason-no-selector"] = { arguments = { { name = "input", type = "string" }, { name = "projector", type = "string" } }, template = "projector '{$projector}' input '{$input}' reads an availability reason argument but its selector is not availability_reason" },
  ["diagnostic-schema-001-projection-reason-type"] = { arguments = { { name = "actual", type = "string" }, { name = "expected", type = "string" }, { name = "input", type = "string" }, { name = "name", type = "string" }, { name = "projector", type = "string" } }, template = "projector '{$projector}' input '{$input}' expects {$expected}, but availability reason argument '{$name}' has {$actual}" },
  ["diagnostic-schema-001-projection-ref-type"] = { arguments = { { name = "actual", type = "string" }, { name = "expected", type = "string" }, { name = "owner", type = "string" }, { name = "projector", type = "string" }, { name = "ref", type = "string" } }, template = "projector '{$projector}' {$owner} expects {$expected}, but {$ref} has {$actual}" },
  ["diagnostic-schema-001-projection-selector-target"] = { arguments = { { name = "target", type = "string" } }, template = "presentation projector uses unsupported metadata target '{$target}'" },
  ["diagnostic-schema-001-provenance-unknown-value"] = { arguments = { { name = "key", type = "string" }, { name = "owner", type = "string" } }, template = "{$owner} provenance key '{$key}' is not a declared value" },
  ["diagnostic-schema-001-query-arg-count"] = { arguments = { { name = "actual", type = "integer" }, { name = "expected", type = "integer" }, { name = "function", type = "string" }, { name = "projector", type = "string" }, { name = "query", type = "string" } }, template = "projector '{$projector}' query '{$query}' passes {$actual} args to projection query function '{$function}', expected {$expected}" },
  ["diagnostic-schema-001-query-max-calls"] = { arguments = { { name = "function", type = "string" } }, template = "projection query function '{$function}' max_calls_per_event must be greater than zero" },
  ["diagnostic-schema-001-read"] = { arguments = { { name = "detail", type = "string" } }, template = "failed to read schema manifest: {$detail}" },
  ["diagnostic-schema-001-remediation-001"] = { arguments = {  } },
  ["diagnostic-schema-001-schema-version-type"] = { arguments = {  }, template = "schema_version must be an integer" },
  ["diagnostic-schema-001-source-generated-field"] = { arguments = { { name = "key", type = "string" } }, template = "generated-only field '{$key}' is not accepted in authoritative TOML" },
  ["diagnostic-schema-001-source-legacy-binding"] = { arguments = {  } },
  ["diagnostic-schema-001-source-non-finite"] = { arguments = {  }, template = "non-finite TOML numbers are not supported" },
  ["diagnostic-schema-001-source-producer-id-empty"] = { arguments = {  }, template = "producer id must not be empty" },
  ["diagnostic-schema-001-source-producer-id-required"] = { arguments = {  }, template = "producer id is required" },
  ["diagnostic-schema-001-source-producer-kind"] = { arguments = {  }, template = "standalone TOML producer kind must be 'standalone'" },
  ["diagnostic-schema-001-source-producer-required"] = { arguments = {  }, template = "a [producer] table with a stable id is required" },
  ["diagnostic-schema-001-source-tagged-field"] = { arguments = { { name = "name", type = "string" } }, template = "availability reason argument '{$name}' contains an unknown tagged field" },
  ["diagnostic-schema-001-toml-decode"] = { arguments = { { name = "detail", type = "string" } }, template = "malformed schema source: {$detail}" },
  ["diagnostic-schema-001-toml-parse"] = { arguments = { { name = "detail", type = "string" } }, template = "malformed schema source: {$detail}" },
  ["diagnostic-schema-001-type-kind"] = { arguments = { { name = "kind", type = "string" }, { name = "type", type = "string" } }, template = "type '{$type}' uses unsupported kind '{$kind}'" },
  ["diagnostic-schema-001-value-origins"] = { arguments = { { name = "owner", type = "string" } }, template = "{$owner} value_origins must map values to origins" },
  ["diagnostic-schema-002-cause-001"] = { arguments = {  } },
  ["diagnostic-schema-002-meaning"] = { arguments = {  } },
  ["diagnostic-schema-002-remediation-001"] = { arguments = {  } },
  ["diagnostic-schema-002-unsupported-version"] = { arguments = { { name = "version", type = "string" } }, template = "unsupported schema manifest version {$version}" },
  ["diagnostic-schema-003-availability-argument"] = { arguments = { { name = "argument", type = "string" }, { name = "condition", type = "string" } }, template = "condition '{$condition}' availability_reason repeats argument '{$argument}'" },
  ["diagnostic-schema-003-cause-001"] = { arguments = {  } },
  ["diagnostic-schema-003-domain-context"] = { arguments = { { name = "context", type = "string" }, { name = "domain", type = "string" } }, template = "metadata domain '{$domain}' repeats context '{$context}'" },
  ["diagnostic-schema-003-duplicate-definition"] = { arguments = { { name = "kind", type = "string" }, { name = "name", type = "string" } }, template = "duplicate {$kind} definition '{$name}'" },
  ["diagnostic-schema-003-effect-mode"] = { arguments = { { name = "effect", type = "string" }, { name = "mode", type = "string" } }, template = "effect '{$effect}' repeats mode '{$mode}'" },
  ["diagnostic-schema-003-label-argument"] = { arguments = { { name = "argument", type = "string" }, { name = "output", type = "string" }, { name = "projector", type = "string" } }, template = "projector '{$projector}' output '{$output}' repeats label argument '{$argument}'" },
  ["diagnostic-schema-003-label-template"] = { arguments = { { name = "template_id", type = "string" } }, template = "duplicate presentation label template id '{$template_id}'" },
  ["diagnostic-schema-003-meaning"] = { arguments = {  } },
  ["diagnostic-schema-003-metadata-target"] = { arguments = { { name = "metadata", type = "string" }, { name = "target", type = "string" } }, template = "metadata '{$metadata}' repeats target '{$target}'" },
  ["diagnostic-schema-003-parameter"] = { arguments = { { name = "owner", type = "string" }, { name = "parameter", type = "string" } }, template = "{$owner} repeats parameter '{$parameter}'" },
  ["diagnostic-schema-003-producer-fingerprint"] = { arguments = { { name = "id", type = "string" }, { name = "kind", type = "string" }, { name = "owner", type = "string" } }, template = "{$owner} repeats producer fingerprint '{$kind}:{$id}'" },
  ["diagnostic-schema-003-projection-field"] = { arguments = { { name = "field", type = "string" }, { name = "output", type = "string" }, { name = "projector", type = "string" } }, template = "projector '{$projector}' output '{$output}' repeats field '{$field}'" },
  ["diagnostic-schema-003-projection-input"] = { arguments = { { name = "input", type = "string" }, { name = "projector", type = "string" } }, template = "projector '{$projector}' repeats input '{$input}'" },
  ["diagnostic-schema-003-projection-output"] = { arguments = { { name = "output", type = "string" }, { name = "projector", type = "string" } }, template = "projector '{$projector}' repeats output '{$output}'" },
  ["diagnostic-schema-003-projection-query"] = { arguments = { { name = "projector", type = "string" }, { name = "query", type = "string" } }, template = "projector '{$projector}' repeats query '{$query}'" },
  ["diagnostic-schema-003-remediation-001"] = { arguments = {  } },
  ["diagnostic-schema-003-required-metadata"] = { arguments = { { name = "key", type = "string" }, { name = "projector", type = "string" } }, template = "projector '{$projector}' repeats required metadata key '{$key}'" },
  ["diagnostic-schema-003-value"] = { arguments = { { name = "owner", type = "string" }, { name = "value", type = "string" } }, template = "{$owner} repeats value '{$value}'" },
  ["diagnostic-schema-004-cause-001"] = { arguments = {  } },
  ["diagnostic-schema-004-contextual-domain-for-flat"] = { arguments = { { name = "domain", type = "string" }, { name = "owner", type = "string" } }, template = "{$owner} references contextual metadata domain '{$domain}', but a flat domain is required" },
  ["diagnostic-schema-004-invalid-condition-return"] = { arguments = { { name = "condition", type = "string" }, { name = "return_type", type = "string" } }, template = "condition '{$condition}' has invalid return type '{$return_type}'" },
  ["diagnostic-schema-004-invalid-metadata-type"] = { arguments = { { name = "metadata", type = "string" }, { name = "type_ref", type = "string" } }, template = "metadata '{$metadata}' has invalid type reference '{$type_ref}'" },
  ["diagnostic-schema-004-invalid-parameter-type"] = { arguments = { { name = "parameter", type = "string" }, { name = "type_ref", type = "string" } }, template = "parameter '{$parameter}' has invalid type reference '{$type_ref}'" },
  ["diagnostic-schema-004-invalid-projection-input-type"] = { arguments = { { name = "input", type = "string" }, { name = "projector", type = "string" }, { name = "type_ref", type = "string" } }, template = "projector '{$projector}' input '{$input}' has invalid type reference '{$type_ref}'" },
  ["diagnostic-schema-004-invalid-projection-output-type"] = { arguments = { { name = "binding", type = "string" }, { name = "output", type = "string" }, { name = "projector", type = "string" }, { name = "type_ref", type = "string" } }, template = "projector '{$projector}' output '{$output}' binding '{$binding}' has invalid type reference '{$type_ref}'" },
  ["diagnostic-schema-004-invalid-query-return-type"] = { arguments = { { name = "function", type = "string" }, { name = "type_ref", type = "string" } }, template = "projection query function '{$function}' has invalid return type '{$type_ref}'" },
  ["diagnostic-schema-004-meaning"] = { arguments = {  } },
  ["diagnostic-schema-004-parameter-special-type"] = { arguments = { { name = "owner", type = "string" }, { name = "parameter", type = "string" }, { name = "type_ref", type = "string" } }, template = "{$owner} parameter '{$parameter}' uses projection-only or metadata-only type reference '{$type_ref}'" },
  ["diagnostic-schema-004-projection-reason-arg"] = { arguments = { { name = "input", type = "string" }, { name = "name", type = "string" }, { name = "projector", type = "string" } }, template = "projector '{$projector}' input '{$input}' references unknown availability reason argument '{$name}'" },
  ["diagnostic-schema-004-remediation-001"] = { arguments = {  } },
  ["diagnostic-schema-004-unknown-availability-reason"] = { arguments = { { name = "condition", type = "string" }, { name = "reason", type = "string" } }, template = "condition '{$condition}' availability_reason references unknown reason '{$reason}'" },
  ["diagnostic-schema-004-unknown-condition-param"] = { arguments = { { name = "condition", type = "string" }, { name = "condition_param", type = "string" } }, template = "condition '{$condition}' availability_reason references unknown condition parameter '{$condition_param}'" },
  ["diagnostic-schema-004-unknown-enum"] = { arguments = { { name = "name", type = "string" }, { name = "owner", type = "string" } }, template = "{$owner} references unknown enum type '{$name}'" },
  ["diagnostic-schema-004-unknown-metadata-domain"] = { arguments = { { name = "domain", type = "string" }, { name = "owner", type = "string" } }, template = "{$owner} references unknown metadata domain '{$domain}'" },
  ["diagnostic-schema-004-unknown-metadata-key"] = { arguments = { { name = "key", type = "string" }, { name = "projector", type = "string" } }, template = "projector '{$projector}' references unknown metadata key '{$key}'" },
  ["diagnostic-schema-004-unknown-projection-reason"] = { arguments = { { name = "projector", type = "string" }, { name = "reason", type = "string" } }, template = "projector '{$projector}' references unknown availability reason '{$reason}'" },
  ["diagnostic-schema-004-unknown-projection-ref"] = { arguments = { { name = "owner", type = "string" }, { name = "projector", type = "string" }, { name = "ref", type = "string" } }, template = "projector '{$projector}' {$owner} references unknown {$ref}" },
  ["diagnostic-schema-004-unknown-query-function"] = { arguments = { { name = "function", type = "string" }, { name = "projector", type = "string" }, { name = "query", type = "string" } }, template = "projector '{$projector}' query '{$query}' references unknown projection query function '{$function}'" },
  ["diagnostic-schema-004-unknown-registry"] = { arguments = { { name = "name", type = "string" }, { name = "owner", type = "string" } }, template = "{$owner} references unknown registry '{$name}'" },
  ["diagnostic-validate-005"] = { arguments = {  }, template = "project must declare exactly one default block" },
  ["diagnostic-validate-005-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-005-help"] = { arguments = {  } },
  ["diagnostic-validate-005-meaning"] = { arguments = {  } },
  ["diagnostic-validate-005-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-006"] = { arguments = { { name = "block_id", type = "string" } }, template = "block `{$block_id}` is another default block" },
  ["diagnostic-validate-006-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-006-help"] = { arguments = {  } },
  ["diagnostic-validate-006-meaning"] = { arguments = {  } },
  ["diagnostic-validate-006-related"] = { arguments = {  } },
  ["diagnostic-validate-006-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-007"] = { arguments = { { name = "reference", type = "string" } }, template = "unknown block reference `{$reference}`" },
  ["diagnostic-validate-007-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-007-meaning"] = { arguments = {  } },
  ["diagnostic-validate-007-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-008-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-008-file"] = { arguments = { { name = "owner", type = "string" } } },
  ["diagnostic-validate-008-meaning"] = { arguments = {  } },
  ["diagnostic-validate-008-order"] = { arguments = { { name = "owner", type = "string" } } },
  ["diagnostic-validate-008-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-009"] = { arguments = { { name = "block_id", type = "string" } }, template = "duplicate block id `{$block_id}`" },
  ["diagnostic-validate-009-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-009-help"] = { arguments = {  } },
  ["diagnostic-validate-009-meaning"] = { arguments = {  } },
  ["diagnostic-validate-009-related"] = { arguments = {  } },
  ["diagnostic-validate-009-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-010"] = { arguments = { { name = "path", type = "string" } }, template = "duplicate source path `{$path}`" },
  ["diagnostic-validate-010-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-010-help"] = { arguments = {  } },
  ["diagnostic-validate-010-meaning"] = { arguments = {  } },
  ["diagnostic-validate-010-related"] = { arguments = {  } },
  ["diagnostic-validate-010-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-011"] = { arguments = { { name = "block_id", type = "string" } }, template = "compiled block id `{$block_id}` must be globally unique" },
  ["diagnostic-validate-011-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-011-help"] = { arguments = {  } },
  ["diagnostic-validate-011-meaning"] = { arguments = {  } },
  ["diagnostic-validate-011-related"] = { arguments = {  } },
  ["diagnostic-validate-011-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-012"] = { arguments = {  }, template = "choice must target a block or END before it can be compiled" },
  ["diagnostic-validate-012-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-012-help"] = { arguments = {  } },
  ["diagnostic-validate-012-meaning"] = { arguments = {  } },
  ["diagnostic-validate-012-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-013"] = { arguments = { { name = "line_id", type = "string" }, { name = "statement_kind", type = "string" } } },
  ["diagnostic-validate-013-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-013-help"] = { arguments = {  } },
  ["diagnostic-validate-013-meaning"] = { arguments = {  } },
  ["diagnostic-validate-013-related"] = { arguments = {  } },
  ["diagnostic-validate-013-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-014"] = { arguments = { { name = "choice_id", type = "string" }, { name = "statement_kind", type = "string" } } },
  ["diagnostic-validate-014-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-014-help"] = { arguments = {  } },
  ["diagnostic-validate-014-meaning"] = { arguments = {  } },
  ["diagnostic-validate-014-related"] = { arguments = {  } },
  ["diagnostic-validate-014-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-015"] = { arguments = { { name = "line_id", type = "string" } }, template = "choice echo references unknown line id `{$line_id}`" },
  ["diagnostic-validate-015-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-015-help"] = { arguments = {  } },
  ["diagnostic-validate-015-meaning"] = { arguments = {  } },
  ["diagnostic-validate-015-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-016-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-016-condition"] = { arguments = {  }, template = "condition argument contains a non-finite float value" },
  ["diagnostic-validate-016-effect"] = { arguments = {  }, template = "effect argument contains a non-finite float value" },
  ["diagnostic-validate-016-help"] = { arguments = {  } },
  ["diagnostic-validate-016-meaning"] = { arguments = {  } },
  ["diagnostic-validate-016-metadata"] = { arguments = { { name = "key", type = "string" } }, template = "metadata value `{$key}` contains a non-finite float value" },
  ["diagnostic-validate-016-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-017"] = { arguments = { { name = "function", type = "string" } }, template = "unknown effect function `{$function}`" },
  ["diagnostic-validate-017-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-017-help"] = { arguments = {  } },
  ["diagnostic-validate-017-meaning"] = { arguments = {  } },
  ["diagnostic-validate-017-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-018"] = { arguments = { { name = "actual", type = "integer" }, { name = "expected", type = "integer" }, { name = "function", type = "string" } } },
  ["diagnostic-validate-018-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-018-help"] = { arguments = {  } },
  ["diagnostic-validate-018-meaning"] = { arguments = {  } },
  ["diagnostic-validate-018-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-019"] = { arguments = { { name = "actual", type = "string" }, { name = "expected", type = "string" }, { name = "function", type = "string" }, { name = "index", type = "integer" } }, template = "argument {$index} for effect `{$function}` expects {$expected}, but got {$actual}" },
  ["diagnostic-validate-019-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-019-meaning"] = { arguments = {  } },
  ["diagnostic-validate-019-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-020"] = { arguments = { { name = "function", type = "string" }, { name = "mode", type = "string" } }, template = "effect `{$function}` does not support {$mode} mode" },
  ["diagnostic-validate-020-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-020-help"] = { arguments = {  } },
  ["diagnostic-validate-020-meaning"] = { arguments = {  } },
  ["diagnostic-validate-020-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-021"] = { arguments = { { name = "expected", type = "string" }, { name = "function", type = "string" }, { name = "index", type = "integer" }, { name = "value", type = "string" } }, template = "argument {$index} for effect `{$function}` uses unknown {$expected} value `{$value}`" },
  ["diagnostic-validate-021-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-021-help"] = { arguments = {  } },
  ["diagnostic-validate-021-meaning"] = { arguments = {  } },
  ["diagnostic-validate-021-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-022"] = { arguments = { { name = "tag", type = "string" } }, template = "unknown inline markup tag `{$tag}`" },
  ["diagnostic-validate-022-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-022-help"] = { arguments = {  } },
  ["diagnostic-validate-022-meaning"] = { arguments = {  } },
  ["diagnostic-validate-022-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-023-bracket"] = { arguments = {  }, template = "unbalanced inline markup tag `[`: missing closing bracket" },
  ["diagnostic-validate-023-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-023-help"] = { arguments = {  } },
  ["diagnostic-validate-023-meaning"] = { arguments = {  } },
  ["diagnostic-validate-023-mismatch"] = { arguments = { { name = "expected_tag", type = "string" }, { name = "tag", type = "string" } }, template = "unbalanced inline markup tag `{$tag}`: expected closing tag for `{$expected_tag}` first" },
  ["diagnostic-validate-023-no-opening"] = { arguments = { { name = "tag", type = "string" } }, template = "unbalanced inline markup tag `{$tag}`: closing tag has no matching opening tag" },
  ["diagnostic-validate-023-related"] = { arguments = {  } },
  ["diagnostic-validate-023-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-023-standalone"] = { arguments = { { name = "tag", type = "string" } }, template = "unbalanced inline markup tag `{$tag}`: standalone tag does not use a closing tag" },
  ["diagnostic-validate-024"] = { arguments = { { name = "tag", type = "string" } }, template = "inline markup tag `{$tag}` requires a closing tag" },
  ["diagnostic-validate-024-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-024-help"] = { arguments = { { name = "tag", type = "string" } } },
  ["diagnostic-validate-024-meaning"] = { arguments = {  } },
  ["diagnostic-validate-024-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-025"] = { arguments = { { name = "child", type = "string" }, { name = "parent", type = "string" } }, template = "inline markup tag `{$parent}` cannot contain nested tag `{$child}`" },
  ["diagnostic-validate-025-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-025-help"] = { arguments = { { name = "child", type = "string" }, { name = "parent", type = "string" } } },
  ["diagnostic-validate-025-meaning"] = { arguments = {  } },
  ["diagnostic-validate-025-related"] = { arguments = {  } },
  ["diagnostic-validate-025-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-026"] = { arguments = { { name = "key", type = "string" } }, template = "unknown metadata key `{$key}`" },
  ["diagnostic-validate-026-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-026-help"] = { arguments = {  } },
  ["diagnostic-validate-026-meaning"] = { arguments = {  } },
  ["diagnostic-validate-026-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-027"] = { arguments = { { name = "key", type = "string" }, { name = "target", type = "string" } }, template = "metadata key `{$key}` is not allowed on {$target}" },
  ["diagnostic-validate-027-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-027-help"] = { arguments = {  } },
  ["diagnostic-validate-027-meaning"] = { arguments = {  } },
  ["diagnostic-validate-027-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-028"] = { arguments = { { name = "key", type = "string" } }, template = "metadata key `{$key}` is not repeatable" },
  ["diagnostic-validate-028-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-028-help"] = { arguments = {  } },
  ["diagnostic-validate-028-meaning"] = { arguments = {  } },
  ["diagnostic-validate-028-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-029"] = { arguments = { { name = "actual", type = "string" }, { name = "expected", type = "string" }, { name = "key", type = "string" } }, template = "metadata key `{$key}` expects {$expected}, but got {$actual}" },
  ["diagnostic-validate-029-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-029-help"] = { arguments = {  } },
  ["diagnostic-validate-029-meaning"] = { arguments = {  } },
  ["diagnostic-validate-029-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-030"] = { arguments = { { name = "expected", type = "string" }, { name = "key", type = "string" }, { name = "value", type = "string" } }, template = "metadata key `{$key}` uses unknown {$expected} value `{$value}`" },
  ["diagnostic-validate-030-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-030-help"] = { arguments = {  } },
  ["diagnostic-validate-030-meaning"] = { arguments = {  } },
  ["diagnostic-validate-030-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-031"] = { arguments = { { name = "domain", type = "string" }, { name = "key", type = "string" }, { name = "value", type = "string" } }, template = "metadata key `{$key}` uses value `{$value}` outside metadata domain `{$domain}`" },
  ["diagnostic-validate-031-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-031-help"] = { arguments = {  } },
  ["diagnostic-validate-031-meaning"] = { arguments = {  } },
  ["diagnostic-validate-031-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-032"] = { arguments = { { name = "domain", type = "string" }, { name = "key", type = "string" }, { name = "selector", type = "string" } }, template = "metadata key `{$key}` cannot resolve selector `{$selector}` for metadata domain `{$domain}`" },
  ["diagnostic-validate-032-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-032-help"] = { arguments = {  } },
  ["diagnostic-validate-032-meaning"] = { arguments = {  } },
  ["diagnostic-validate-032-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-033"] = { arguments = { { name = "key", type = "string" }, { name = "selector", type = "string" } }, template = "metadata key `{$key}` has ambiguous or non-symbol selector `{$selector}`" },
  ["diagnostic-validate-033-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-033-help"] = { arguments = {  } },
  ["diagnostic-validate-033-meaning"] = { arguments = {  } },
  ["diagnostic-validate-033-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-034"] = { arguments = { { name = "function", type = "string" } }, template = "unknown condition function `{$function}`" },
  ["diagnostic-validate-034-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-034-help"] = { arguments = {  } },
  ["diagnostic-validate-034-meaning"] = { arguments = {  } },
  ["diagnostic-validate-034-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-035"] = { arguments = { { name = "actual", type = "integer" }, { name = "expected", type = "integer" }, { name = "function", type = "string" } } },
  ["diagnostic-validate-035-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-035-help"] = { arguments = {  } },
  ["diagnostic-validate-035-meaning"] = { arguments = {  } },
  ["diagnostic-validate-035-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-036"] = { arguments = { { name = "actual", type = "string" }, { name = "expected", type = "string" }, { name = "function", type = "string" }, { name = "index", type = "integer" } }, template = "argument {$index} for condition `{$function}` expects {$expected}, but got {$actual}" },
  ["diagnostic-validate-036-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-036-meaning"] = { arguments = {  } },
  ["diagnostic-validate-036-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-037"] = { arguments = { { name = "expected", type = "string" }, { name = "function", type = "string" }, { name = "index", type = "integer" }, { name = "value", type = "string" } }, template = "argument {$index} for condition `{$function}` uses unknown {$expected} value `{$value}`" },
  ["diagnostic-validate-037-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-037-help"] = { arguments = {  } },
  ["diagnostic-validate-037-meaning"] = { arguments = {  } },
  ["diagnostic-validate-037-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-038-bool"] = { arguments = { { name = "actual", type = "string" }, { name = "function", type = "string" } }, template = "condition `{$function}` returns {$actual}, but bool is required" },
  ["diagnostic-validate-038-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-038-enum"] = { arguments = { { name = "actual", type = "string" }, { name = "function", type = "string" } }, template = "condition `{$function}` returns {$actual}, but enum is required" },
  ["diagnostic-validate-038-meaning"] = { arguments = {  } },
  ["diagnostic-validate-038-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-039"] = { arguments = { { name = "reason", type = "string" } }, template = "unknown availability reason `{$reason}`" },
  ["diagnostic-validate-039-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-039-help"] = { arguments = {  } },
  ["diagnostic-validate-039-meaning"] = { arguments = {  } },
  ["diagnostic-validate-039-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-040"] = { arguments = { { name = "reason", type = "string" } }, template = "availability reason override `{$reason}` must be parameterless" },
  ["diagnostic-validate-040-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-040-help"] = { arguments = {  } },
  ["diagnostic-validate-040-meaning"] = { arguments = {  } },
  ["diagnostic-validate-040-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-041"] = { arguments = { { name = "reason", type = "string" } }, template = "availability reason `{$reason}` requires a choice requires=(...) clause" },
  ["diagnostic-validate-041-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-041-meaning"] = { arguments = {  } },
  ["diagnostic-validate-041-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-042"] = { arguments = { { name = "detail", type = "string" } }, template = "PO placeholder mismatch: {$detail}" },
  ["diagnostic-validate-042-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-042-meaning"] = { arguments = {  } },
  ["diagnostic-validate-042-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-043-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-043-contiguous-arms"] = { arguments = {  }, template = "plural entries require contiguous msgstr[N] arms" },
  ["diagnostic-validate-043-count"] = { arguments = { { name = "actual", type = "integer" }, { name = "expected", type = "integer" } }, template = "header declares {$expected} plural arms but entry has {$actual}" },
  ["diagnostic-validate-043-expected-arm"] = { arguments = { { name = "expected", type = "integer" } }, template = "expected msgstr[{$expected}]" },
  ["diagnostic-validate-043-invalid-arm"] = { arguments = { { name = "keyword", type = "string" } }, template = "invalid plural arm `{$keyword}`" },
  ["diagnostic-validate-043-meaning"] = { arguments = {  } },
  ["diagnostic-validate-043-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-043-requires-plural-source"] = { arguments = {  }, template = "msgstr[N] requires msgid_plural" },
  ["diagnostic-validate-044-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-044-duplicate-or-empty"] = { arguments = { { name = "key", type = "string" } }, template = "duplicate or empty header `{$key}`" },
  ["diagnostic-validate-044-invalid-plural-forms"] = { arguments = {  }, template = "Plural-Forms must declare positive nplurals and a plural expression" },
  ["diagnostic-validate-044-invalid-plural-rule"] = { arguments = { { name = "detail", type = "string" } }, template = "Plural-Forms rule is unusable: {$detail}" },
  ["diagnostic-validate-044-meaning"] = { arguments = {  } },
  ["diagnostic-validate-044-missing-colon"] = { arguments = { { name = "line", type = "string" } }, template = "header line `{$line}` lacks `:`" },
  ["diagnostic-validate-044-multiple-headers"] = { arguments = {  }, template = "PO document contains multiple header records" },
  ["diagnostic-validate-044-plural-header-required"] = { arguments = {  }, template = "active plural entries require Plural-Forms with nplurals and plural" },
  ["diagnostic-validate-044-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-045-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-045-duplicate"] = { arguments = { { name = "key", type = "string" } }, template = "invalid interpolation binding: placeholder `{$key}` is declared more than once" },
  ["diagnostic-validate-045-invalid-name"] = { arguments = { { name = "key", type = "string" } }, template = "invalid interpolation binding: invalid placeholder name '{$key}'" },
  ["diagnostic-validate-045-meaning"] = { arguments = {  } },
  ["diagnostic-validate-045-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-045-unbound"] = { arguments = { { name = "key", type = "string" } }, template = "invalid interpolation binding: placeholder `{$key}` has no binding" },
  ["diagnostic-validate-045-unescaped"] = { arguments = {  }, template = "invalid interpolation binding: unescaped closing brace" },
  ["diagnostic-validate-045-unterminated"] = { arguments = {  }, template = "invalid interpolation binding: unterminated placeholder" },
  ["diagnostic-validate-045-unused"] = { arguments = { { name = "key", type = "string" } }, template = "invalid interpolation binding: binding `{$key}` is not used in the text" },
  ["diagnostic-validate-046-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-046-cause-002"] = { arguments = {  } },
  ["diagnostic-validate-046-cause-003"] = { arguments = {  } },
  ["diagnostic-validate-046-cause-004"] = { arguments = {  } },
  ["diagnostic-validate-046-count-type"] = { arguments = {  }, template = "invalid plural line: the `count` binding must have type `int`" },
  ["diagnostic-validate-046-meaning"] = { arguments = {  } },
  ["diagnostic-validate-046-missing-count"] = { arguments = {  }, template = "invalid plural line: plural lines require `bind=(count:int=$value)`" },
  ["diagnostic-validate-046-newline"] = { arguments = {  }, template = "invalid plural line: plural lines must contain exactly one singular and one plural body line" },
  ["diagnostic-validate-046-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-046-remediation-002"] = { arguments = {  } },
  ["diagnostic-validate-046-remediation-003"] = { arguments = {  } },
  ["diagnostic-validate-046-remediation-004"] = { arguments = {  } },
  ["diagnostic-validate-047"] = { arguments = { { name = "actual", type = "string" }, { name = "expected", type = "string" }, { name = "tag", type = "string" } }, template = "translation changes attributes for inline markup tag `{$tag}`: expected `{$expected}`, got `{$actual}`" },
  ["diagnostic-validate-047-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-047-meaning"] = { arguments = {  } },
  ["diagnostic-validate-047-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-048"] = { arguments = { { name = "tag", type = "string" } }, template = "translation introduces inline markup tag `{$tag}` not present in the source value" },
  ["diagnostic-validate-048-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-048-meaning"] = { arguments = {  } },
  ["diagnostic-validate-048-remediation-001"] = { arguments = {  } },
  ["diagnostic-validate-049"] = { arguments = { { name = "tag", type = "string" } }, template = "translation is missing required inline markup tag `{$tag}` from the source value" },
  ["diagnostic-validate-049-cause-001"] = { arguments = {  } },
  ["diagnostic-validate-049-meaning"] = { arguments = {  } },
  ["diagnostic-validate-049-remediation-001"] = { arguments = {  } },
}
