cli-help-about = Recite dialogue compiler and validation CLI.
cli-help-usage-heading = Usage:
cli-help-commands-heading = Commands
cli-help-options-heading = Options
cli-help-command-compile = Compile dialogue source to a MessagePack .recitec artefact
cli-help-command-play = Play a compiled asset interactively
cli-help-arg-output-compile = Write MessagePack compiled asset bytes to this path
cli-help-arg-asset-play = MessagePack .recitec asset to play
cli-help-arg-ui = Interactive UI mode
cli-help-arg-help = Show help
