message_ids! {
    CliHelpAbout, CliHelpUsageHeading, CliHelpCommandsHeading, CliHelpArgumentsHeading, CliHelpOptionsHeading,
    CliHelpCommandValidate, CliHelpCommandCompile, CliHelpCommandExtract, CliHelpCommandCheckIds, CliHelpCommandCheckMarkup,
    CliHelpCommandCheckMetadata, CliHelpCommandValidateProject, CliHelpCommandCheckFresh, CliHelpCommandInspectSchema, CliHelpCommandExplain, CliHelpCommandWatch,
    CliHelpCommandRun, CliHelpCommandTrace, CliHelpCommandPlay, CliHelpCommandBench, CliHelpArgPaths,
    CliHelpArgSchema, CliHelpArgSchemaInspection, CliHelpArgProjectRoot, CliHelpArgDiagnosticCode, CliHelpArgOutputCompile, CliHelpArgOutputExtract,
    CliHelpArgAssetRun, CliHelpArgAssetPlay, CliHelpArgBlock, CliHelpArgFixture, CliHelpArgUi,
    CliHelpArgKeymap, CliHelpArgDialogueLocale, CliHelpArgDialogueCatalog, CliHelpArgBenchScale, CliHelpArgBenchGroup,
    CliHelpArgBenchFormat, CliHelpArgBenchOutput, CliHelpArgBenchBaseline, CliHelpArgBenchSamples, ExplainCode,
    ExplainCategory, ExplainMeaning, ExplainCommonCauses, ExplainHowToFix, ExplainListItem,
    WatchBuilding, WatchWaitingForChanges, WatchRebuilding, WatchBuildSucceeded, WatchBuildDuration, WatchBuildFailedWaiting,
    WatchBuildFailed,
    WatchBuildFailedPartial, WatchBuildFailedIndeterminate, WatchBuildFailedRefused,
    WatchBuildFailedNotAttempted, WatchBuildFailedPublished, WatchBuildFailedUnsupported,
    WatchBuildFailedPartialWithFailure, WatchBuildFailedIndeterminateWithFailure,
    WatchBuildFailedRefusedWithFailure, WatchBuildFailedNotAttemptedWithFailure,
    WatchBuildFailedPublishedWithFailure, WatchBuildFailedUnsupportedWithFailure,
    WatchBuildStatusSucceeded, WatchBuildStatusFailed, WatchBuildStatusStale,
    WatchBuildStatusCancelled, WatchBuildStatusSuperseded, WatchBuildStatusUnknown,
    WatchBuildRecoveryTargetsEmpty, WatchBuildRecoveryTargetsList,
    WatchBuildRecoveryRequired, WatchBuildRecoveryNotice, WatchBuildRecoverySummary,
    WatchBuildRecoveryRecord, WatchBuildRecoveryReasonStageCleanup,
    WatchBuildRecoveryReasonPublicationIndeterminate, WatchBuildRecoveryReasonPublicationUncommitted,
    WatchBuildRecoveryReasonUnknown,
    WatchBuildRecoveryDetailIo,
    WatchBuildRecoveryIoAlreadyExists, WatchBuildRecoveryIoInvalidInput,
    WatchBuildRecoveryIoNotFound, WatchBuildRecoveryIoPermissionDenied,
    WatchBuildRecoveryIoOther,
    WatchBuildFailureCheckRequestMismatch, WatchBuildFailureCheckFreshnessMismatch,
    WatchBuildFailureCheckUnknown, WatchBuildFailureDiagnostics, WatchBuildFailureUnknown,
    WatchBuildFailureEngineInvalidOutput,
    WatchBuildFailureEngineHost, WatchBuildFailureEngineUnknown, WatchBuildFailureDuplicateTarget,
    WatchBuildFailurePreparation, WatchBuildFailureReasonRejected, WatchBuildFailureReasonStorage,
    WatchBuildFailureReasonUnknown, WatchBuildFailureInvalidPublishedPartition,
    WatchBuildFailureInvalidPartialPartition, WatchBuildFailureInvalidRecoveryTarget,
    WatchBuildFailureInvalidNotCommitted, WatchBuildFailureInvalidUnknown,
    WatchBuildFailureRefusalStaleBuildGeneration,
    WatchBuildFailureRefusalStaleSnapshotGeneration, WatchBuildFailureRefusalStaleFingerprints,
    WatchBuildFailureRefusalRequestIdentityMismatch, WatchBuildFailureNotAttemptedBuildFailed,
    WatchBuildFailureNotAttemptedCancelled, WatchBuildFailureNotAttemptedSuperseded,
    WatchBuildFailureNotAttemptedStale, WatchBuildFailureNotAttemptedNoCandidates,
    WatchBuildFailureNotAttemptedPreparationFailed, WatchBuildFailureNotAttemptedInvalidOutcome,
    WatchBuildFailureNotAttemptedUnknown, WatchBuildFailureRefusalUnknown,
    WatchEventError, CliHelpArgHelp, CliHelpArgVersion, PlayTuiStarting,
    PlayStart, PlayLine, PlayPromptLine, PlayPrompt, PlayChoiceRow,
    PlayChoicePrompt, PlayConditionPrompt, PlayConditionResult, PlaySelectedChoice, PlayEffect,
    PlayAckPrompt, PlayAckCompleted, PlayEnd, PlayDeferredEffects, PlayDeferredEffectRow,
    PlayInvalidInput, PlayErrorEnterYOrN, PlayErrorEnterEnumVariant, PlayErrorPressEnterOrAck, PlayErrorEmptyChoice,
    PlayErrorChoiceIndexOutOfRange, PlayErrorChoiceIdInvalid, PlayErrorChoiceIdUnavailable, PlayErrorChoiceUnavailable, PlayErrorChoiceUnavailableReason,
    RunEffect, TuiReady, TuiFinished, TuiCommand, TuiCommandWithValue,
    TuiUnknownCommand, TuiChoiceInputPrefix, TuiChoiceInput, TuiEnumVariantInput, TuiConditionYesRow,
    TuiConditionNoRow, TuiConditionYesShortcutRow, TuiConditionNoShortcutRow, TuiEnumConditionHint, TuiAckEnterHint,
    TuiHeaderTitle, TuiHeaderAsset, TuiHeaderBlock, TuiWaiting, TuiMetadataMode,
    TuiMetadataRuntimeEffectId, TuiMetadataFunction, TuiMetadataArgs, TuiInputAnswer, TuiInputEnumVariant,
    TuiInputAck, TuiInputChoice, TuiChoiceUnavailable, TuiChoiceUnavailableReason, TuiDeferredQueueTitle,
    TuiDeferredQueueScheduled, TuiDeferredQueueReadyAtEnd, TuiTranscriptLine, TuiTranscriptPrompt, TuiTranscriptChoice,
    TuiTranscriptCondition, TuiTranscriptEffect, TuiTranscriptAck, TuiTranscriptDeferred, TuiTranscriptEnd,
    TuiTranscriptCompleted, TuiTranscriptEffectText, TuiTranscriptDeferredEffectText, TuiTranscriptDeferredEffects, TuiHelpTitle,
    TuiHelpKeyHeading, TuiHelpActionHeading, TuiHelpDescriptionHeading, TuiHelpActionClose, TuiHelpActionQuit,
    TuiHelpActionMove, TuiHelpActionSubmit, TuiHelpActionInput, TuiHelpActionShortcut, TuiHelpActionCommand,
    TuiHelpActionHelp, TuiHelpActionQueue, TuiHelpDescriptionClose, TuiHelpDescriptionOpenHelp, TuiHelpDescriptionQuit,
    TuiHelpDescriptionInterrupt, TuiHelpDescriptionMoveChoice, TuiHelpDescriptionSubmitChoice, TuiHelpDescriptionInputChoice, TuiHelpDescriptionMoveCondition,
    TuiHelpDescriptionShortcutCondition, TuiHelpDescriptionSubmitCondition, TuiHelpDescriptionInputEnumCondition, TuiHelpDescriptionSubmitEnumCondition, TuiHelpDescriptionSubmitEffect,
    TuiHelpDescriptionFinished, TuiHelpDescriptionCommand, TuiHelpDescriptionQueue, TuiFooterCommand, CliErrorPlayEof,
    CliErrorPlayInvalidInput, CliErrorPlayInterrupted, CliErrorPlayTuiRequiresTerminal, CliErrorUiConfigRead, CliErrorUiConfigToml,
    CliErrorUiLocaleInvalid, CliErrorDialogueCatalogConflict, CliErrorDialogueCatalogPluralFormsConflict, CliErrorDialogueCatalogMalformed, CliErrorDialogueCatalogMissingLocale,
    CliErrorDialogueCatalogSpecInvalid, CliErrorDialogueLocaleInvalid, CliErrorGeneric, CliErrorDiagnosticRendering, CliErrorDiagnosticCodeMalformed,
    CliErrorDiagnosticCodeUnknown, CliErrorUiCatalog, CliErrorBench, CliErrorBenchmark, CliErrorDialogueCatalogReasonExpectedDirective,
    CliErrorDialogueCatalogReasonExpectedQuotedString, CliErrorDialogueCatalogReasonMissingContext, CliErrorDialogueCatalogReasonMissingId, CliErrorDialogueCatalogReasonMissingTranslation, CliErrorDialogueCatalogReasonInvalidHeader, CliErrorDialogueCatalogReasonInvalidPluralRule,
    CliErrorDialogueCatalogReasonInvalidStableId, CliErrorDialogueCatalogReasonDuplicateField, CliErrorDialogueCatalogReasonDuplicateEntry, CliErrorDialogueCatalogReasonInvalidFieldOrder, CliErrorDialogueCatalogReasonPlaceholderMismatch,
    CliErrorDialogueCatalogReasonPluralEntriesUnsupported, CliErrorDialogueCatalogReasonQuotedContinuationWithoutField, CliErrorDialogueCatalogReasonUnexpectedTextAfterQuotedString, CliErrorDialogueCatalogReasonUnterminatedQuotedString, CliErrorDialogueCatalogReasonUnsupportedEscape,
    CliErrorDecodeAsset, CliErrorAssetMetadata, CliErrorAssetNotFile, CliErrorMalformedCompiledAsset, CliErrorDiagnostics,
    CliErrorFixtureChoiceIndex, CliErrorFixtureChoiceNotInPrompt, CliErrorAmbiguousFixtureChoice, CliErrorFixtureToml, CliErrorMissingPath, CliErrorMissingFixtureChoice,
    CliErrorNoInputs, CliErrorOutputOverwritesInput, CliErrorBlockingEffect, CliErrorBenchJson, CliErrorTraceJson,
    CliErrorSchemaInspectionJson, CliErrorSchemaInspectionUnsupportedFormat, CliErrorSchemaInspectionMalformed, CliErrorSchemaInspectionInvalidSummary,
    CliErrorUnknownPrompt, CliErrorRead, CliErrorReadDir, CliErrorWrite, CliErrorWatch,
    LspHoverRequires, LspHoverIf, LspHoverSpeaker, LspHoverSpeakerWithDisplayName, LspHoverMetadata,
    LspHoverMetadataWithDomain, LspHoverCondition, LspHoverEffect, LspHoverProjectionQuery, LspHoverPresentationProjector,
    LspHoverPresentationOutput, LspHoverPresentationLabel, LspHoverBlock, LspHoverRegistry, LspHoverMetadataDomain,
    LspHoverAvailabilityReason, LspHoverRegistryValue, LspHoverEnumValue, LspHoverDomainValue, LspHoverProducedBy,
    LspHoverSchemaProducer, LspHoverSchemaFreshness, LspHoverSchemaFreshnessState, LspHoverSchemaFreshnessStatus, LspHoverSchemaFreshnessUnavailable, LspHoverSchemaScopedFingerprints, LspCompletionAvailabilityReason, LspCompletionBlock,
    LspCompletionSpeaker, LspCompletionMetadataKey, LspCompletionMetadataKeyWithDomain, LspCompletionMetadataDomain, LspCompletionCondition,
    LspCompletionConditionDocumentation, LspCompletionEffect, LspCompletionEffectDocumentation, LspCompletionProjectionQuery, LspCompletionProjectionQueryDocumentation,
    LspCompletionProjectionQueryFunction, LspCompletionProjectionQueryCall, LspCompletionProjectionInput, LspCompletionProjector, LspCompletionOutput,
    LspCompletionLabel, LspCodeActionInsertMissingId, LspCodeActionInsertAllMissingIds, LspCodeActionCreateBlockStub, LspCodeActionAddCondition,
    LspCodeActionAddEffect, LspCodeActionSchemaAction, LspCodeActionSchemaDisabled, LspWarningUiConfig,
}
