[package]
name = "recite-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Core Recite AST, identifiers, values, diagnostics, and schema model."
license.workspace = true
repository.workspace = true
readme.workspace = true

[features]
default = []
small-ids = ["dep:compact_str"]

[dependencies]
blake3.workspace = true
compact_str = { workspace = true, optional = true }
rmp-serde.workspace = true
serde.workspace = true
serde_bytes.workspace = true
serde-value.workspace = true
serde_json.workspace = true
thiserror.workspace = true
toml.workspace = true
unicode-ident.workspace = true

[lints]
workspace = true
