[package]
name = "recite-writer-model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
recite-compiler.workspace = true
recite-core.workspace = true
recite-parser.workspace = true
recite-runtime.workspace = true
thiserror.workspace = true
serde = { version = "1", features = ["derive"] }

[lints]
workspace = true
