[package]
name = "recite-writer-model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
recite-compiler.workspace = true
recite-core.workspace = true
recite-parser.workspace = true
recite-runtime.workspace = true
thiserror.workspace = true
serde = { version = "1", features = ["derive", "rc"] }

[lints]
workspace = true

[features]
benchmarks = []
heap-profile = ["benchmarks"]

[dev-dependencies]
dhat = "0.3.3"
criterion = { version = "0.8.2", default-features = false }
serde_json = "1"

[[bench]]
name = "large_project"
harness = false
required-features = ["benchmarks"]
