use super::DiagnosticExplanation;
use crate::DiagnosticCategory;

pub(super) const EXPLANATIONS: &[DiagnosticExplanation] = &[
    DiagnosticExplanation::new(
        "RECITE_VALIDATE005",
        DiagnosticCategory::Validation,
        "The compiled project has no default block.",
        &["No block is marked as the default start point."],
        &["Mark exactly one block as default or provide an explicit start block where required."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE006",
        DiagnosticCategory::Validation,
        "The compiled project has more than one default block.",
        &["Multiple blocks were marked as default."],
        &["Keep one default block and remove the extra default markers."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE007",
        DiagnosticCategory::Validation,
        "A divert or reference points at an unknown block.",
        &["The target block was renamed, removed, or misspelled."],
        &["Update the reference or add the missing block."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE008",
        DiagnosticCategory::Validation,
        "A compiled source span is invalid.",
        &["Source map data has an impossible line, column, or range."],
        &["Report this as a compiler bug with the source that produced it."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE009",
        DiagnosticCategory::Validation,
        "Two blocks use the same block ID.",
        &["A block was copied or renamed to an existing ID."],
        &["Give each block a unique ID."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE010",
        DiagnosticCategory::Validation,
        "The same source path appears more than once in one compile input set.",
        &["The same file was passed directly and through a directory scan."],
        &["Remove the duplicate input path."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE011",
        DiagnosticCategory::Validation,
        "A compiled block ID is ambiguous.",
        &["Two source files compile blocks with the same runtime block ID."],
        &["Rename one block or split the runtime lookup contract in a future format version."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE012",
        DiagnosticCategory::Validation,
        "A choice is missing its runtime target.",
        &["The choice does not identify a block, branch, or end target."],
        &["Add the intended choice target."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE013",
        DiagnosticCategory::Validation,
        "A line contains a nested statement that the current compiled asset format cannot represent.",
        &["A prompt line contains a nested statement other than a supported choice."],
        &["Keep only nested choices under prompt lines for v0 compiled assets."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE014",
        DiagnosticCategory::Validation,
        "A choice contains a nested statement that the current compiled asset format cannot represent.",
        &["A choice body contains unsupported nested control flow or statements."],
        &["Keep choice bodies to text and one target divert for v0 compiled assets."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE015",
        DiagnosticCategory::Validation,
        "A choice echo references an unknown line.",
        &["The echo line ID does not exist in the compiled dialogue."],
        &["Use an existing line ID, `echo=selected_text`, or `echo=none`."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE016",
        DiagnosticCategory::Validation,
        "A numeric value is not finite.",
        &["A schema, metadata, condition, or effect value produced NaN or infinity."],
        &["Replace the value with a finite number."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE017",
        DiagnosticCategory::Validation,
        "An effect call names an unknown effect function.",
        &["The effect function is misspelled or missing from the schema."],
        &["Declare the effect in the schema or correct the function name."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE018",
        DiagnosticCategory::Validation,
        "An effect call has the wrong number of arguments.",
        &["The call does not match the parameter count declared by the schema."],
        &["Add, remove, or reorder arguments to match the schema."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE019",
        DiagnosticCategory::Validation,
        "An effect call argument has the wrong type.",
        &["A literal argument does not match the effect parameter type."],
        &["Change the argument value or update the schema parameter type."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE020",
        DiagnosticCategory::Validation,
        "An effect call uses an unsupported effect mode.",
        &["The effect mode is not one of the modes accepted for that schema effect."],
        &["Use an effect mode supported by the effect declaration."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE021",
        DiagnosticCategory::Validation,
        "An effect call argument names a value that the schema does not export.",
        &[
            "An effect argument refers to an enum, registry, speaker, or other schema value that is unknown.",
        ],
        &["Use a value exported in the project schema manifest."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE022",
        DiagnosticCategory::Markup,
        "Inline text uses an unknown markup tag.",
        &["The tag is misspelled or missing from the schema markup declarations."],
        &["Fix the tag name or declare it in the schema."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE023",
        DiagnosticCategory::Markup,
        "Inline markup tags are not balanced.",
        &["A closing tag does not match the most recent open tag."],
        &["Reorder or rename the tags so each opening tag closes correctly."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE024",
        DiagnosticCategory::Markup,
        "An inline markup tag is missing its closing tag.",
        &["A tagged span reaches the end of the line while still open."],
        &["Add the missing closing tag or remove the opening tag."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE025",
        DiagnosticCategory::Markup,
        "Inline markup nesting is invalid.",
        &["The tag order creates an unsupported overlap or nesting shape."],
        &["Rewrite the markup so tags nest cleanly."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE026",
        DiagnosticCategory::Metadata,
        "Metadata uses a key that the schema does not know.",
        &["The key is misspelled or missing from the schema metadata declarations."],
        &["Declare the metadata key in the schema or correct the key name."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE027",
        DiagnosticCategory::Metadata,
        "Metadata appears on a target where that key is not allowed.",
        &["The key is valid but not for this block, line, choice, or project context."],
        &["Move the metadata or update the schema target list."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE028",
        DiagnosticCategory::Metadata,
        "Metadata repeats a key that must be unique for that target.",
        &["The same metadata key was written more than once where repeats are forbidden."],
        &["Remove the duplicate or change the schema if repeated values are intended."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE029",
        DiagnosticCategory::Metadata,
        "A metadata value has the wrong type.",
        &["The source value does not match the type declared by the schema."],
        &["Change the value or update the metadata declaration type."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE030",
        DiagnosticCategory::Metadata,
        "A metadata value is outside the allowed domain.",
        &["The value is not one of the allowed symbols, registry values, or contextual values."],
        &["Use an allowed value or update the schema domain."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE031",
        DiagnosticCategory::Metadata,
        "A metadata value is outside a metadata domain snapshot.",
        &["The value is not one of the symbols exported by the resolved metadata domain."],
        &["Use a symbol exported in the metadata domain snapshot or update the domain."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE032",
        DiagnosticCategory::Metadata,
        "A metadata domain selector is missing required context.",
        &["The metadata location does not provide the context needed to resolve the selector."],
        &["Provide the selector context, move the metadata, or update the missing-context policy."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE033",
        DiagnosticCategory::Metadata,
        "A metadata domain selector has ambiguous or non-symbol context.",
        &["The selector context resolves to zero, multiple, or non-symbol scalar values."],
        &["Change the context so the selector resolves to exactly one scalar symbol value."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE034",
        DiagnosticCategory::Validation,
        "A condition call names an unknown condition function.",
        &["The condition function is misspelled or missing from the schema."],
        &["Declare the condition in the schema or correct the function name."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE035",
        DiagnosticCategory::Validation,
        "A condition call has the wrong number of arguments.",
        &["The call does not match the parameter count declared by the schema."],
        &["Add, remove, or reorder arguments to match the schema."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE036",
        DiagnosticCategory::Validation,
        "A condition call argument has the wrong type.",
        &["A literal argument does not match the condition parameter type."],
        &["Change the argument value or update the schema parameter type."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE037",
        DiagnosticCategory::Validation,
        "A condition call argument value is not exported by the schema.",
        &[
            "A condition argument names an enum, registry, speaker, or other schema value that is unknown.",
        ],
        &["Use a value exported in the project schema manifest."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE038",
        DiagnosticCategory::Validation,
        "A condition returns a value kind that is not valid in this expression context.",
        &[
            "A non-boolean condition is used where a boolean result is required, or a boolean condition is used as a match scrutinee.",
        ],
        &["Use a condition with the return type required by the expression context."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE039",
        DiagnosticCategory::Validation,
        "A choice availability reason override names an unknown reason.",
        &[
            "The reason override is misspelled or missing from the schema availability reason declarations.",
        ],
        &[
            "Declare the availability reason in the project schema manifest or correct the reason name.",
        ],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE040",
        DiagnosticCategory::Validation,
        "A choice availability reason override names a parameterized reason.",
        &[
            "The reason template requires parameters, but direct `reason=` overrides cannot bind them.",
        ],
        &["Use a parameterless reason override or model the reason through a condition mapping."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE041",
        DiagnosticCategory::Validation,
        "A choice availability reason appears without a requirement.",
        &[
            "A choice declares an availability reason but has no `requires=(...)` clause to make it unavailable.",
        ],
        &["Add the required choice condition or remove the unused reason override."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE042",
        DiagnosticCategory::Validation,
        "A PO translation does not preserve the source placeholders.",
        &["A translated value is missing a named interpolation or introduces an extra one."],
        &["Keep the same placeholder names in the corresponding PO translation."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE043",
        DiagnosticCategory::Validation,
        "A PO plural record has invalid translation arms.",
        &["Plural arms are missing, out of order, duplicated, or inconsistent with the header."],
        &["Provide contiguous `msgstr[N]` arms matching the locale's declared plural count."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE044",
        DiagnosticCategory::Validation,
        "A PO header is malformed.",
        &[
            "A header line is missing its key/value separator, is duplicated, or has invalid plural metadata.",
        ],
        &["Correct the header while retaining the rest of the catalogue source."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE045",
        DiagnosticCategory::Validation,
        "A source interpolation binding is malformed or does not match its text.",
        &[
            "A placeholder is undeclared, a binding is unused or duplicated, or the text contains invalid brace syntax; all are blocking v1 validation errors.",
        ],
        &["Declare each placeholder with `bind=(name:type=$value)` and escape literal braces."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE046",
        DiagnosticCategory::Validation,
        "A plural dialogue line does not meet the source shape required for plural selection.",
        &[
            "The plural source forms do not have the required two-form body shape.",
            "The singular or plural form contains a newline instead of exactly one body line.",
            "A plural line has no `bind=(count:int=$value)` binding.",
            "The `count` binding uses a type other than `int`.",
        ],
        &[
            "Provide exactly one singular body line and one immediately following `|` continuation.",
            "Keep the singular and plural forms to one body line each.",
            "Declare the count source with `bind=(count:int=$value)`.",
            "Change the `count` binding type to `int`.",
        ],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE047",
        DiagnosticCategory::Validation,
        "A PO translation changes an inline markup tag's attributes.",
        &["Translated markup must preserve the attributes authored in the source value."],
        &["Keep each translated tag's attributes identical to its source tag."],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE048",
        DiagnosticCategory::Validation,
        "A PO translation introduces an inline markup tag that is absent from the source value.",
        &["Translated markup may not add tag occurrences that the source value did not author."],
        &[
            "Remove the introduced tag or add the tag to the source value before extracting translations.",
        ],
    ),
    DiagnosticExplanation::new(
        "RECITE_VALIDATE049",
        DiagnosticCategory::Validation,
        "A PO translation omits an inline markup tag required by the source value.",
        &[
            "Translated markup must preserve every source tag occurrence, even when prose is reordered.",
        ],
        &["Restore the missing tag occurrence in the translated value."],
    ),
];
