[package]
name = "recite-compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Recite compiler, validator, POT extractor, and compiled asset writer."
license.workspace = true
repository.workspace = true
readme.workspace = true

[features]
default = []
bench-support = []

[dependencies]
recite-core.workspace = true
recite-parser.workspace = true
rmp-serde.workspace = true
serde.workspace = true
serde_bytes.workspace = true
serde_json.workspace = true
thiserror.workspace = true
unic-langid.workspace = true

[dev-dependencies]
insta.workspace = true
recite-ui.workspace = true
serde-value.workspace = true

[lints]
workspace = true
