//! Emit the typed diagnostic resources owned by the VS Code projections.
//!
//! The checked-in editor projection is derived from this executable's
//! `UiContract::default()` view, not from Fluent placeholder spelling.

use recite_ui::{Client, UiArgType, all_resource_specs};

fn main() {
    println!("# Generated by export-vscode-diagnostic-contract; do not edit.");
    for resource in all_resource_specs().into_iter().filter(|resource| {
        resource.id.as_str().starts_with("diagnostic-")
            && resource.clients.contains(&Client::VsCode)
            && resource.clients.contains(&Client::VsCodium)
        }) {
        if resource.arguments.is_empty() {
            println!("{}", resource.id.as_str());
        } else {
            for (name, kind) in resource.arguments {
                println!("{}\t{}\t{}", resource.id.as_str(), name, kind_name(kind));
            }
        }
    }
}

fn kind_name(kind: UiArgType) -> &'static str {
    match kind {
        UiArgType::String => "string",
        UiArgType::Integer => "integer",
        UiArgType::Float => "float",
        UiArgType::Boolean => "boolean",
    }
}
