[package]
name = "recite-bakeoff-floem"
version = "0.0.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[workspace]

[dependencies]
recite-bakeoff-authoring = { path = "../../crates/authoring" }
floem = "=0.2.0"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"

[profile.dev]
debug = 0
