[package]
name = "recite-parser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Recite DSL parser and source mapping."
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
recite-core.workspace = true
rowan = "0.16"

[dev-dependencies]
proptest.workspace = true
insta.workspace = true
recite-ui.workspace = true

[lints]
workspace = true
