[package]
name = "recite-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Deterministic Recite runtime with no engine dependencies."
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
recite-core.workspace = true
rmp-serde.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
recite-compiler.workspace = true
serde_json.workspace = true
serde-value.workspace = true

[lints]
workspace = true
