[package]
name = "recite-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Command-line interface for Recite projects."
license.workspace = true
repository.workspace = true
readme.workspace = true

[[bin]]
name = "recite"
path = "src/main.rs"

[dependencies]
clap.workspace = true
crossterm.workspace = true
notify.workspace = true
ratatui.workspace = true
recite-core.workspace = true
recite-parser.workspace = true
recite-compiler.workspace = true
recite-benchmarks = { version = "0.1.0", path = "../recite-benchmarks" }
recite-runtime.workspace = true
recite-ui.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
unic-langid.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
