#ifndef RECITE_H
#define RECITE_H

/* Generated with cbindgen:0.29.4 */

/* Generated by scripts/generate-ffi-header.sh. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#define RECITE_OK RECITE_STATUS_OK
#define RECITE_ERR_VALIDATION RECITE_STATUS_VALIDATION
#define RECITE_ERR_ASSET_LOAD_OR_DECODE RECITE_STATUS_ASSET_LOAD_OR_DECODE
#define RECITE_ERR_STALE_OR_INCOMPATIBLE RECITE_STATUS_STALE_OR_INCOMPATIBLE
#define RECITE_ERR_SCHEMA_MISMATCH RECITE_STATUS_SCHEMA_MISMATCH
#define RECITE_ERR_NO_ACTIVE_SESSION RECITE_STATUS_NO_ACTIVE_SESSION
#define RECITE_ERR_SESSION_ALREADY_ACTIVE RECITE_STATUS_SESSION_ALREADY_ACTIVE
#define RECITE_ERR_UNKNOWN_START_BLOCK RECITE_STATUS_UNKNOWN_START_BLOCK
#define RECITE_ERR_INVALID_CHOICE RECITE_STATUS_INVALID_CHOICE
#define RECITE_ERR_UNAVAILABLE_CHOICE RECITE_STATUS_UNAVAILABLE_CHOICE
#define RECITE_ERR_STALE_CHOICE RECITE_STATUS_STALE_CHOICE
#define RECITE_ERR_MISSING_CONDITION_HANDLER RECITE_STATUS_MISSING_CONDITION_HANDLER
#define RECITE_ERR_CONDITION_EVALUATION RECITE_STATUS_CONDITION_EVALUATION
#define RECITE_ERR_INVALID_CONDITION_RESULT RECITE_STATUS_INVALID_CONDITION_RESULT
#define RECITE_ERR_EFFECT_ACKNOWLEDGEMENT RECITE_STATUS_EFFECT_ACKNOWLEDGEMENT
#define RECITE_ERR_REJECTED_REFRESH RECITE_STATUS_REJECTED_REFRESH
#define RECITE_ERR_SAVE_LOAD_INCOMPATIBILITY RECITE_STATUS_SAVE_LOAD_INCOMPATIBILITY
#define RECITE_ERR_LOCALISATION RECITE_STATUS_LOCALISATION
#define RECITE_ERR_MISSING_PROJECTION_HANDLER RECITE_STATUS_MISSING_PROJECTION_HANDLER
#define RECITE_ERR_PROJECTION_EVALUATION RECITE_STATUS_PROJECTION_EVALUATION
#define RECITE_ERR_INVALID_PROJECTION_RESULT RECITE_STATUS_INVALID_PROJECTION_RESULT
#define RECITE_ERR_INVALID_HANDLE RECITE_STATUS_INVALID_HANDLE
#define RECITE_ERR_DIALOGUE_FAULT RECITE_STATUS_DIALOGUE_FAULT


/**
 * ABI major version for the generated C header.
 *
 * Increment this for breaking C ABI changes.
 */
#define RECITE_FFI_VERSION_MAJOR 0

/**
 * ABI minor version for additive, backwards-compatible C ABI changes.
 */
#define RECITE_FFI_VERSION_MINOR 0

/**
 * ABI patch version for documentation-only or implementation-only releases.
 */
#define RECITE_FFI_VERSION_PATCH 1

/**
 * Stable C error codes. Matches the category table in docs/c-abi-boundary-design.md.
 *
 * Add a new variant only when a new contract §12 category is introduced.
 * Never renumber existing variants — that breaks compiled host bindings.
 */
enum ReciteStatus
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    RECITE_STATUS_OK = 0,
    RECITE_STATUS_VALIDATION = -1,
    RECITE_STATUS_ASSET_LOAD_OR_DECODE = -2,
    RECITE_STATUS_STALE_OR_INCOMPATIBLE = -3,
    RECITE_STATUS_SCHEMA_MISMATCH = -4,
    RECITE_STATUS_NO_ACTIVE_SESSION = -5,
    RECITE_STATUS_SESSION_ALREADY_ACTIVE = -6,
    RECITE_STATUS_UNKNOWN_START_BLOCK = -7,
    RECITE_STATUS_INVALID_CHOICE = -8,
    RECITE_STATUS_UNAVAILABLE_CHOICE = -9,
    RECITE_STATUS_STALE_CHOICE = -10,
    RECITE_STATUS_MISSING_CONDITION_HANDLER = -11,
    RECITE_STATUS_CONDITION_EVALUATION = -12,
    RECITE_STATUS_INVALID_CONDITION_RESULT = -13,
    RECITE_STATUS_EFFECT_ACKNOWLEDGEMENT = -14,
    RECITE_STATUS_REJECTED_REFRESH = -15,
    RECITE_STATUS_SAVE_LOAD_INCOMPATIBILITY = -16,
    RECITE_STATUS_LOCALISATION = -17,
    RECITE_STATUS_MISSING_PROJECTION_HANDLER = -18,
    RECITE_STATUS_PROJECTION_EVALUATION = -19,
    RECITE_STATUS_INVALID_PROJECTION_RESULT = -20,
    RECITE_STATUS_INVALID_HANDLE = -21,
    RECITE_STATUS_DIALOGUE_FAULT = -22,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum ReciteStatus ReciteStatus;
#else
typedef int32_t ReciteStatus;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Heap-allocated byte buffer returned by `recite-ffi`.
 *
 * The host must call `recite_buffer_free` exactly once after consuming the
 * data. The buffer is allocated by Rust's global allocator; do not free it
 * with a different allocator.
 *
 * # Safety
 * Freeing with the wrong allocator (e.g. the Unity C runtime's `free`) is
 * undefined behaviour. Always link against `recite-ffi` as a pre-built
 * `.dll`/`.so`; never recompile it per backend or link it statically into
 * a Unity player separately.
 */
typedef struct {
    uint8_t *data;
    size_t len;
} ReciteBuffer;

/**
 * Result returned by a `ReciteConditionFn` callback.
 *
 * When `ok != 0`, `value_msgpack` must point to a msgpack-encoded
 * `FfiConditionValue` valid for the duration of the callback frame.
 * When `ok == 0`, `error_message` must point to a UTF-8 NUL-terminated string
 * valid for the duration of the callback frame.
 */
typedef struct {
    /**
     * 1 = success, 0 = failure.
     */
    uint8_t ok;
    /**
     * Host-owned msgpack bytes encoding a `FfiConditionValue`. Valid when `ok != 0`.
     */
    const uint8_t *value_msgpack;
    size_t value_len;
    /**
     * Host-owned UTF-8 NUL-terminated error message. Valid when `ok == 0`.
     */
    const char *error_message;
} ReciteConditionResult;

/**
 * Query passed to a `ReciteConditionFn` callback.
 *
 * All pointers are borrowed for the duration of the callback and must not be
 * stored by the host.
 */
typedef struct {
    /**
     * UTF-8 NUL-terminated condition function name. Borrowed for the call.
     */
    const char *function_name;
    /**
     * Msgpack-encoded array of `FfiConditionArg` values. Borrowed for the call.
     */
    const uint8_t *args_msgpack;
    size_t args_len;
} ReciteConditionQuery;

/**
 * Host-provided condition handler function pointer.
 *
 * Invoked synchronously on the same thread as the `recite_session_*` call
 * that triggers condition evaluation. Must not call back into `recite-ffi`.
 */
typedef ReciteConditionResult (*ReciteConditionFn)(const ReciteConditionQuery *query, void *userdata);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Frees an asset handle.
 *
 * If sessions that reference this asset are still alive, their internal
 * `Arc` reference keeps the underlying data alive until those sessions are
 * also freed.
 */
void recite_asset_free(uint64_t asset_handle);

/**
 * Loads and decodes a compiled Recite asset from a byte slice.
 *
 * On success writes a non-zero handle to `*asset_handle_out` and returns
 * `RECITE_OK`. On failure returns a negative status code and sets the
 * thread-local error message.
 *
 * The asset handle is valid until `recite_asset_free` is called.
 *
 * # Safety
 * `bytes` must be valid for `len` bytes. `asset_handle_out` must be a valid
 * non-null pointer.
 */
ReciteStatus recite_asset_load(const uint8_t *bytes, size_t len, uint64_t *asset_handle_out);

/**
 * Frees a buffer allocated by `recite-ffi`.
 *
 * # Safety
 * `buf` must have been produced by a `recite-ffi` function and must not have
 * been freed already.
 */
void recite_buffer_free(ReciteBuffer *buf);

/**
 * Returns a pointer to the last error message set on the current thread.
 * The pointer is valid until the next `recite-ffi` call on this thread.
 * Returns a pointer to a NUL-terminated empty string (never null) if no error
 * has been set, so callers can always safely pass the result to C string APIs.
 */
const char *recite_last_error_message(void);

/**
 * Acknowledges the currently pending blocking effect.
 *
 * `effect_request_id` is a UTF-8 NUL-terminated string matching the effect ID
 * emitted in the output batch. `ack_completed` is 1 for `EffectAck::Completed`
 * or 0 for `EffectAck::Failed`. `failure_reason` is a nullable UTF-8
 * NUL-terminated string used when `ack_completed == 0`.
 *
 * # Safety
 * All non-null pointer arguments must be valid for the duration of the call.
 */
ReciteStatus recite_session_acknowledge_effect(uint64_t session_handle,
                                               const char *effect_request_id,
                                               uint8_t ack_completed,
                                               const char *failure_reason,
                                               ReciteBuffer *batch_out);

/**
 * Runs the initial traversal drain for a session created with
 * `recite_session_create`.
 *
 * Must be called exactly once per session, after all condition handlers have
 * been registered with `recite_session_register_condition`. On success writes
 * the first output batch to `*batch_out`.
 *
 * # Safety
 * `batch_out` must be a valid non-null pointer.
 */
ReciteStatus recite_session_begin(uint64_t session_handle, ReciteBuffer *batch_out);

/**
 * Selects a pending prompt choice.
 *
 * `choice_id` is a UTF-8 NUL-terminated string. On success writes the
 * subsequent output batch to `*batch_out`.
 *
 * # Safety
 * All non-null pointer arguments must be valid for the duration of the call.
 */
ReciteStatus recite_session_choose(uint64_t session_handle,
                                   const char *choice_id,
                                   ReciteBuffer *batch_out);

/**
 * Creates a session handle without running any traversal.
 *
 * Use this instead of `recite_session_start` when conditions appear in the
 * opening block of the scene: register handlers with
 * `recite_session_register_condition` after this call, then call
 * `recite_session_begin` to run the first traversal drain.
 *
 * `start_block` and `locale` are nullable UTF-8 NUL-terminated strings.
 * On success writes a non-zero handle to `*session_handle_out`.
 *
 * # Safety
 * All non-null pointer arguments must be valid for the duration of the call.
 */
ReciteStatus recite_session_create(uint64_t asset_handle,
                                   const char *start_block,
                                   const char *locale,
                                   uint64_t *session_handle_out);

/**
 * Frees a session handle. Does nothing if the handle is unknown.
 */
void recite_session_free(uint64_t session_handle);

/**
 * Registers a condition handler on an existing session handle.
 *
 * For conditions that appear in the opening block of a scene, call this
 * after `recite_session_create` and before `recite_session_begin`. For
 * conditions that only appear in later blocks (e.g. after a choice), it is
 * also safe to register after `recite_session_start` returns.
 *
 * `name` is a UTF-8 NUL-terminated condition function name. `userdata` is
 * passed back to the handler on each invocation.
 *
 * # Safety
 * `name` must be valid NUL-terminated UTF-8 for the duration of the call.
 * `userdata` must remain valid and accessible from the calling thread for the
 * session's lifetime.
 */
ReciteStatus recite_session_register_condition(uint64_t session_handle,
                                               const char *name,
                                               ReciteConditionFn handler,
                                               void *userdata);

/**
 * Restores a session from a snapshot previously produced by
 * `recite_session_snapshot`.
 *
 * The snapshot must have been produced against the same compiled asset
 * identified by `asset_handle`. On success writes a new session handle to
 * `*session_handle_out` and a resumption output batch to `*batch_out`. The
 * batch is empty when the restored session is at a pending-prompt or
 * pending-effect boundary (the host re-presents state from its own copy).
 * If the snapshot encoded an ended session, `recite_session_restore` returns
 * `RECITE_ERR_NO_ACTIVE_SESSION`.
 *
 * # Safety
 * All non-null pointer arguments must be valid for the duration of the call.
 */
ReciteStatus recite_session_restore(uint64_t asset_handle,
                                    const uint8_t *snapshot_bytes,
                                    size_t snapshot_len,
                                    uint64_t *session_handle_out,
                                    ReciteBuffer *batch_out);

/**
 * Encodes the current session state as an opaque msgpack snapshot.
 *
 * The snapshot bytes are written to a freshly allocated `ReciteBuffer`; the
 * host must call `recite_buffer_free` after consuming them.
 *
 * # Safety
 * `snapshot_out` must be a valid non-null pointer.
 */
ReciteStatus recite_session_snapshot(uint64_t session_handle, ReciteBuffer *snapshot_out);

/**
 * Convenience that combines `recite_session_create` and `recite_session_begin`.
 *
 * Use this when no conditions appear in the opening block of the scene. For
 * scenes that evaluate conditions at scene start, use `recite_session_create`
 * + `recite_session_register_condition` + `recite_session_begin` instead.
 *
 * `start_block` and `locale` are nullable UTF-8 NUL-terminated strings.
 * On success writes a non-zero handle to `*session_handle_out` and the initial
 * output batch to `*batch_out`.
 *
 * # Safety
 * All non-null pointer arguments must be valid for the duration of the call.
 */
ReciteStatus recite_session_start(uint64_t asset_handle,
                                  const char *start_block,
                                  const char *locale,
                                  uint64_t *session_handle_out,
                                  ReciteBuffer *batch_out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RECITE_H */
