// Generated by GN build/gen.py for commit 6e8dcdebbadf4f8aa75e6a4b6e0bdf89dce1513a.
#ifndef OUT_LAST_COMMIT_POSITION_H_
#define OUT_LAST_COMMIT_POSITION_H_
#define LAST_COMMIT_POSITION_NUM 2354
#define LAST_COMMIT_POSITION "2354 (6e8dcdebbadf)"
#endif  // OUT_LAST_COMMIT_POSITION_H_
